import { withBasePath } from "./base-path";
import type {
  PublicEvent,
  PublicProgram,
  PublicResearch,
  PublicStats,
} from "./types";

export const homeStats: PublicStats = {
  totalEvents: 98,
  totalParticipants: 2045,
  totalPrograms: 13,
  totalResearch: 6,
};

export const programs: PublicProgram[] = [
  {
    id: 1,
    slug: "cai-research-fellowship-2026",
    name: "Cooperative AI Research Fellowship 2026",
    type: "fellowship",
    startDate: "2026-01-01",
    endDate: "2026-04-01",
    totalParticipants: 10,
    description:
      "The fellowship was a full-time 3-month research program for participants from diverse backgrounds around the world to pursue AI safety research from a cooperative AI perspective. The fellowship ran from January to April 2026 in Cape Town, South Africa, and kicked off with a week-long retreat. While working from the AI Safety Cape Town co-working space, participants received mentorship from top researchers in the field of cooperative AI, including from organisations such as Google DeepMind, the University of Oxford, and MIT. Alongside this, participants were provided with resources for building their knowledge and network in cooperative AI, and financial support covering their living and travel expenses. The aim of this program was to prepare fellows for research careers in cooperative AI, and to support the burgeoning AI safety and cooperative AI ecosystem in South Africa. In line with this, the University of Cape Town (UCT) launched the African AI Safety Hub at the UCT AI Initiative.",
    websiteUrl: "https://www.cai-research-fellowship.com/",
    image: {
      alt: "Cooperative AI Research Fellowship 2026 participants",
      url: withBasePath("/images/programs/cai-research-fellowship-2026.webp"),
    },
    partners: [
      {
        id: 1,
        name: "Cooperative AI Foundation",
      },
      {
        id: 2,
        name: "University of Cape Town AI Initiative",
      },
      {
        id: 3,
        name: "Lambda, The Superintelligence Cloud",
      },
      {
        id: 4,
        name: "Principles of Intelligence",
      },
    ],
  },
  {
    id: 2,
    slug: "intro-to-transformative-ai-apr-2025",
    name: "Intro Transformative AI - April 2025",
    type: "course",
    startDate: "2025-04-01",
    endDate: "2025-05-01",
    totalParticipants: 8,
    description:
      "BlueDot's Intro to Transformative AI Course. The second iteration of our Intro to TAI course, where we hosted a 5-day course in collaboration with BlueDot at our coworking offices at Innovation City. We ran multiple cohorts, with a mix of in-person and online cohorts to make the program more accessible.",
    image: {
      alt: "Intro to Transformative AI April 2025 cohort",
      url: withBasePath("/images/programs/intro-to-transformative-ai-apr-2025.webp"),
    },
    cohorts: [
      {
        id: 1,
        name: "Intro to TAI April 2025 - JHB Cohort",
        slug: "intro-tai-apr-2025-jhb",
        startDate: "2025-04-01",
        endDate: "2025-05-01",
      },
      {
        id: 2,
        name: "Intro to TAI April 2025 - CPT Cohort",
        slug: "intro-tai-apr-2025-cpt",
        startDate: "2025-04-01",
        endDate: "2025-05-01",
        acceptedCount: 8,
        averageRating: 9.5,
      },
    ],
  },
  {
    id: 3,
    slug: "intro-coop-ai-2025-q2",
    name: "Intro to Cooperative AI - Q2 2025",
    type: "course",
    startDate: "2025-04-01",
    endDate: "2025-07-01",
    totalParticipants: 16,
    description:
      "Introduction to Cooperative AI Course by The Cooperative AI Foundation. We ran a 13 week program covering the Cooperative AI Curriculum from the Cooperative AI Foundation. This was the first official in-person cohort of the program ever.",
    image: {
      alt: "Intro to Cooperative AI Q2 2025 session",
      url: withBasePath("/images/programs/intro-coop-ai-2025-q2.webp"),
    },
    cohorts: [
      {
        id: 3,
        name: "Intro to Cooperative AI Q2 2025 - Cohort 1",
        slug: "intro-coop-ai-q2-2025-c1",
        startDate: "2025-04-01",
        endDate: "2025-07-01",
        acceptedCount: 8,
      },
      {
        id: 4,
        name: "Intro to Cooperative AI Q2 2025 - Cohort 2",
        slug: "intro-coop-ai-q2-2025-c2",
        startDate: "2025-05-01",
        endDate: "2025-06-01",
        acceptedCount: 8,
      },
    ],
    partners: [
      {
        id: 1,
        name: "Cooperative AI Foundation",
      },
    ],
  },
  {
    id: 4,
    slug: "intro-tai-2025-feb",
    name: "Intro to Transformative AI - February 2025",
    type: "course",
    startDate: "2025-02-01",
    endDate: "2025-02-01",
    totalParticipants: 24,
    description:
      "BlueDot's Intro to Transformative AI Course. First official in-person cohort ever. We hosted a 5-day course in collaboration with BlueDot at our coworking offices at Innovation City. One of the participants wrote about his experience of the course, another quit his job to work on AI Safety, and another is joining our research group to work with us on a research project.",
    image: {
      alt: "Intro to Transformative AI February 2025 cohort",
      url: withBasePath("/images/programs/intro-tai-2025-feb.webp"),
    },
    cohorts: [
      {
        id: 5,
        name: "Intro to TAI February 2025 - Cohort 1",
        slug: "intro-tai-feb-2025-c1",
        startDate: "2025-02-01",
        endDate: "2025-02-01",
        acceptedCount: 36,
        averageRating: 9.5,
      },
    ],
    partners: [
      {
        id: 1,
        name: "BlueDot Impact",
      },
    ],
  },
  {
    id: 5,
    slug: "stellies-ai-safety",
    name: "Stellies AI Safety",
    type: "volunteer_program",
    startDate: "2025-01-01",
    totalParticipants: 12,
    description:
      "Seeded Stellenbosch AI Safety (Stellies AI Safety). Elected community organisers - Boyd Kane (Lead), Nicholas Lombard. Hosted First Meetup.",
    image: {
      alt: "Stellies AI Safety launch event",
      url: withBasePath("/images/programs/stellies-ai-safety.webp"),
    },
  },
  {
    id: 6,
    slug: "condor-camp-2024",
    name: "Condor Initiative x AI Safety Cape Town Retreat",
    type: "retreat",
    startDate: "2024-11-01",
    endDate: "2024-11-01",
    totalParticipants: 28,
    description:
      "Condor Camp aimed to deepen participants' understanding of the AI Safety (AIS) landscape, expose them to concrete career paths, and foster a sense of self-efficacy in pursuing AIS-related opportunities. By providing a low-stakes environment for exploration, the camp encouraged participants to experiment with different career directions, build connections with experts, and develop a clearer sense of their next steps.",
    websiteUrl: "https://www.condorinitiative.org/ccsa",
    image: {
      alt: "Condor Initiative x AI Safety Cape Town Retreat",
      url: withBasePath("/images/programs/condor-camp-2024.webp"),
    },
    partners: [
      {
        id: 1,
        name: "Condor Initiative",
      },
    ],
  },
  {
    id: 7,
    slug: "ai-safety-wits",
    name: "AI Safety WITS",
    type: "volunteer_program",
    startDate: "2024-01-01",
    totalParticipants: 23,
    description:
      "Seeded AI Safety University of Witwatersrand (AI Safety WITS). Hosted the first meetup: 23 people attended the event. One person provided feedback on the feedback form, rating the event 10/10.",
    image: {
      alt: "AI Safety WITS launch meetup",
      url: withBasePath("/images/programs/ai-safety-wits.webp"),
    },
  },
];

export const research: PublicResearch[] = [
  {
    id: 1,
    slug: "precursors-proxies-predictive-models",
    title: "Precursors, Proxies, and Predictive Models for Long-Horizon Tasks",
    status: "published",
    authors: [
      {
        authorName: "Jaco Du Toit",
      },
      {
        authorName: "Leo Hyams",
      },
      {
        authorName: "Daniil Anisimov",
      },
      {
        authorName: "Samuel Brown",
      },
    ],
    acceptedVenue:
      "Workshop on Evaluating the Evolving LLM Lifecycle: Benchmarks, Emergent Abilities, and Scaling at NeurIPS 2025",
    arxivLink: "https://openreview.net/forum?id=bfX0oa2XDr",
  },
  {
    id: 2,
    slug: "synthetic-environment-detection-eval",
    title: "Synthetic Environment Detection Eval",
    status: "accepted",
    authors: [
      {
        authorName: "Jaco Du Toit",
      },
      {
        authorName: "Leo Hyams",
      },
      {
        authorName: "Asa Strickland Cooper",
      },
      {
        authorName: "Joshua Olive",
      },
    ],
    acceptedVenue: "UK AISI ARA Stream Bounty Programme",
  },
  {
    id: 3,
    slug: "situational-awareness-eval",
    title: "Situational Awareness Eval",
    status: "accepted",
    authors: [
      {
        authorName: "Noah De Nicola",
      },
      {
        authorName: "Leo Hyams",
      },
      {
        authorName: "Benjamin Sturgeon",
      },
      {
        authorName: "Jaco Du Toit",
      },
      {
        authorName: "Jay Bailey",
      },
      {
        authorName: "Alexandra Abbas",
      },
    ],
    acceptedVenue: "UK AISI ARA Stream Bounty Programme",
  },
  {
    id: 4,
    slug: "rl-manipulation-eval",
    title: "RL Manipulation Eval",
    status: "accepted",
    authors: [
      {
        authorName: "Jaco Du Toit",
      },
      {
        authorName: "Leo Hyams",
      },
      {
        authorName: "Celia Waggoner",
      },
    ],
    acceptedVenue: "UK AISI ARA Stream Bounty Programme",
  },
  {
    id: 5,
    slug: "efficient-test-time-cot-eval",
    title: "Efficient Test-Time Chain of Thought Eval",
    status: "accepted",
    authors: [
      {
        authorName: "Jaco Du Toit",
      },
      {
        authorName: "Leo Hyams",
      },
      {
        authorName: "Celia Waggoner",
      },
    ],
    acceptedVenue: "UK AISI ARA Stream Bounty Programme",
  },
  {
    id: 6,
    slug: "humanagencybench",
    title: "HumanAgencyBench: Do Language Models Support Human Agency?",
    status: "published",
    authors: [
      {
        authorName: "Benjamin Sturgeon",
      },
      {
        authorName: "Leo Hyams",
      },
      {
        authorName: "Daniel Samuelson",
      },
      {
        authorName: "Ethan Vorster",
      },
      {
        authorName: "Jacob Haimes",
      },
      {
        authorName: "Jacy Reese Anthis",
      },
    ],
    acceptedVenue: "HEAL workshop at CHI 2026",
    arxivLink: "https://arxiv.org/abs/2509.08494",
  },
];

export const events: PublicEvent[] = [
  {
    id: 1,
    name: "Cooperative AI Research Fellowship Closing Showcase",
    type: "talk",
    eventDate: "2026-04-24",
    location: "The Hasso Plattner School of Design Thinking Afrika",
    attendanceCount: 113,
    image: null,
    slug: "cooperative-ai-research-fellowship-closing-showcase",
  },
  {
    id: 2,
    name: "AI Safety Research Workshop",
    type: "workshop",
    eventDate: "2026-03-27",
    location: "School for Data Science and Computational Thinking",
    attendanceCount: 15,
    image: null,
    slug: "ai-safety-research-workshop",
  },
  {
    id: 3,
    name: "AI Safety SA 2026 Kick Off Event",
    type: "talk",
    eventDate: "2026-02-20",
    location: "Workshop17 Kloof Street",
    attendanceCount: 80,
    image: null,
    slug: "ai-safety-sa-2026-kick-off-event",
  },
  {
    id: 4,
    name: "Reading Group: Reasoning Models Struggle to Control their Chains of Thought",
    type: "reading_group",
    eventDate: "2026-05-20",
    location: "Workshop17 Kloof Street",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-reasoning-models-struggle-to-control-their-cha",
  },
  {
    id: 5,
    name: "Reading Group: Gradual Disempowerment",
    type: "reading_group",
    eventDate: "2026-05-13",
    location: "Workshop17 Kloof Street",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-gradual-disempowerment",
  },
  {
    id: 6,
    name: "Reading Group: It's just distributed computing: Rethinking AI governance",
    type: "reading_group",
    eventDate: "2026-05-06",
    location: "Workshop17 Kloof Street",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-it-s-just-distributed-computing-rethinking-ai-",
  },
  {
    id: 7,
    name: "ShockLab Seminar: Assessing AI-Amplified Counterfeit Medicine Threats in Africa",
    type: "seminar",
    eventDate: "2026-04-29",
    location: "UCT Department of Mathematics and Applied Mathematics",
    attendanceCount: 1,
    image: null,
    slug: "shocklab-seminar-assessing-ai-amplified-counterfeit-medicine",
  },
  {
    id: 8,
    name: "ML4Good SA Community Social \ud83c\udf89",
    type: "meetup",
    eventDate: "2026-04-29",
    location: "Our Local Kloof Street",
    attendanceCount: 12,
    image: null,
    slug: "ml4good-sa-community-social",
  },
  {
    id: 9,
    name: "ShockLab Seminar: Inter-agent Influence Evaluation & Embedded Adversarial Agent in Multi-Agent LLM Systems",
    type: "seminar",
    eventDate: "2026-04-22",
    location: "UCT Department of Mathematics and Applied Mathematics",
    attendanceCount: 2,
    image: null,
    slug: "shocklab-seminar-inter-agent-influence-evaluation-embedded-a",
  },
  {
    id: 10,
    name: "Reading Group: Emotion Concepts and their Function in a Large Language Model",
    type: "reading_group",
    eventDate: "2026-04-15",
    location: "Workshop17 Kloof Street",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-emotion-concepts-and-their-function-in-a-large",
  },
  {
    id: 11,
    name: "ShockLab Seminar: Strategic Vagueness in LLMS",
    type: "seminar",
    eventDate: "2026-04-15",
    location: "UCT Department of Mathematics and Applied Mathematics",
    attendanceCount: 2,
    image: null,
    slug: "shocklab-seminar-strategic-vagueness-in-llms",
  },
  {
    id: 12,
    name: "CAIRF Seminar Series: You can't study game theoretic dynamics if you can't compute equilibria | Eugene Vinitsky",
    type: "seminar",
    eventDate: "2026-04-09",
    location: "Workshop17 Kloof Street",
    attendanceCount: 8,
    image: null,
    slug: "cairf-seminar-series-you-can-t-study-game-theoretic-dynamics",
  },
  {
    id: 13,
    name: "Reading Group: Applying Cognitive Design Patterns to General LLM Agents",
    type: "reading_group",
    eventDate: "2026-04-08",
    location: "Workshop17 Kloof Street",
    attendanceCount: 3,
    image: null,
    slug: "reading-group-applying-cognitive-design-patterns-to-general-",
  },
  {
    id: 14,
    name: "Reading Group: Symbiotic Alignment via Collective Predictive Coding",
    type: "reading_group",
    eventDate: "2026-04-01",
    location: "Workshop17 Kloof Street",
    attendanceCount: 7,
    image: null,
    slug: "reading-group-symbiotic-alignment-via-collective-predictive-",
  },
  {
    id: 15,
    name: "ShockLab Seminar: Similarity as a Signal: Do Al Agents Cooperate More When They Know They're Alike?",
    type: "seminar",
    eventDate: "2026-04-01",
    location: "UCT Department of Mathematics and Applied Mathematics",
    attendanceCount: 5,
    image: null,
    slug: "shocklab-seminar-similarity-as-a-signal-do-al-agents-coopera",
  },
  {
    id: 16,
    name: "Reading Group: The Artificial Self: Characterising the landscape of AI identity",
    type: "reading_group",
    eventDate: "2026-03-25",
    location: "Workshop17 Kloof Street",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-the-artificial-self-characterising-the-landsca",
  },
  {
    id: 17,
    name: "CAIRF Seminar Series: Beyond Meditations on Moloch | Ashley Hodgson",
    type: "seminar",
    eventDate: "2026-03-25",
    location: "Workshop17 Kloof Street",
    attendanceCount: 6,
    image: null,
    slug: "cairf-seminar-series-beyond-meditations-on-moloch-ashley-hod",
  },
  {
    id: 18,
    name: "Reading Group: Words That Make Language Models Perceive",
    type: "reading_group",
    eventDate: "2026-03-18",
    location: "Workshop17 Kloof Street",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-words-that-make-language-models-perceive",
  },
  {
    id: 19,
    name: "Reading Group: The Persona Selection Model: Why AI Assistants might Behave like Humans",
    type: "reading_group",
    eventDate: "2026-03-11",
    location: "Workshop17 Kloof Street",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-the-persona-selection-model-why-ai-assistants-",
  },
  {
    id: 20,
    name: "ShockLab Seminar: Delegating Deliberation to Agents",
    type: "seminar",
    eventDate: "2026-03-11",
    location: "UCT Department of Mathematics and Applied Mathematics",
    attendanceCount: 13,
    image: null,
    slug: "shocklab-seminar-delegating-deliberation-to-agents",
  },
  {
    id: 21,
    name: "Reading Group: LLMs Miss the Multi-Agent Mark",
    type: "reading_group",
    eventDate: "2026-03-04",
    location: "Workshop17 Kloof Street",
    attendanceCount: 6,
    image: null,
    slug: "reading-group-llms-miss-the-multi-agent-mark",
  },
  {
    id: 22,
    name: "Reading Group: Governing AI Agents",
    type: "reading_group",
    eventDate: "2026-02-25",
    location: "Workshop17 Kloof Street",
    attendanceCount: 7,
    image: null,
    slug: "reading-group-governing-ai-agents",
  },
  {
    id: 23,
    name: "Chai & Connect: Africans @ India AI Impact Summit Social",
    type: "meetup",
    eventDate: "2026-02-20",
    location: "Cafe Lota, India",
    attendanceCount: 6,
    image: null,
    slug: "chai-connect-africans-india-ai-impact-summit-social",
  },
  {
    id: 24,
    name: "Toward Collective Action: Roundtable on Safe & Trusted AI in Africa",
    type: "other",
    eventDate: "2026-02-20",
    location: "Bharat Mandapam, India",
    attendanceCount: 31,
    image: null,
    slug: "toward-collective-action-roundtable-on-safe-trusted-ai-in-af",
  },
  {
    id: 25,
    name: "Reading Group: AI Tools for Existential Security",
    type: "reading_group",
    eventDate: "2026-02-18",
    location: "Workshop17 Kloof Street",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-ai-tools-for-existential-security",
  },
  {
    id: 26,
    name: "Reading Group: The Assistant Axis",
    type: "reading_group",
    eventDate: "2026-02-11",
    location: "Workshop17 Kloof Street",
    attendanceCount: 6,
    image: null,
    slug: "reading-group-the-assistant-axis",
  },
  {
    id: 27,
    name: "Reading Group: Safety Cases for Frontier AI",
    type: "reading_group",
    eventDate: "2026-01-28",
    location: "Workshop17 Kloof Street",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-safety-cases-for-frontier-ai",
  },
  {
    id: 28,
    name: "Reading Group: LLMs Report Subjective Experience Under Self-Referential Processing",
    type: "reading_group",
    eventDate: "2026-01-21",
    location: "Workshop17 Kloof Street",
    attendanceCount: 9,
    image: null,
    slug: "reading-group-llms-report-subjective-experience-under-self-r",
  },
  {
    id: 29,
    name: "Reading Group: Lessons from Complexity Theory for AI Governance",
    type: "reading_group",
    eventDate: "2026-01-14",
    location: "Workshop17 Kloof Street",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-lessons-from-complexity-theory-for-ai-governan",
  },
  {
    id: 30,
    name: "Reading Group: The Evidence for AI Consciousness, Today",
    type: "reading_group",
    eventDate: "2026-01-07",
    location: "Workshop17 Kloof Street",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-the-evidence-for-ai-consciousness-today",
  },
  {
    id: 31,
    name: "Reading Group: Natural Selection Favors AIs over Humans",
    type: "reading_group",
    eventDate: "2025-12-17",
    location: "Innovation City Cape Town",
    attendanceCount: 8,
    image: null,
    slug: "reading-group-natural-selection-favors-ais-over-humans",
  },
  {
    id: 32,
    name: "Community Update & Lightning Talks",
    type: "talk",
    eventDate: "2025-12-12",
    location: "Innovation City Cape Town",
    attendanceCount: 15,
    image: null,
    slug: "community-update-lightning-talks",
  },
  {
    id: 33,
    name: "Reading Group: Toward a Safe Internet of Agents",
    type: "reading_group",
    eventDate: "2025-12-10",
    location: "Innovation City Cape Town",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-toward-a-safe-internet-of-agents",
  },
  {
    id: 34,
    name: "Reading Group: Disrupting the First AI-Orchestrated Cyber Espionage Campaign",
    type: "reading_group",
    eventDate: "2025-12-03",
    location: "Innovation City Cape Town",
    attendanceCount: 6,
    image: null,
    slug: "reading-group-disrupting-the-first-ai-orchestrated-cyber-esp",
  },
  {
    id: 35,
    name: "AISSA Community Hike\ud83c\udf32",
    type: "other",
    eventDate: "2025-11-29",
    location: "East Fort, Chapman's Peak",
    attendanceCount: 10,
    image: null,
    slug: "aissa-community-hike",
  },
  {
    id: 36,
    name: "Reading Group: AI Can Help Humans Find Common Ground in Democratic Deliberation",
    type: "reading_group",
    eventDate: "2025-11-26",
    location: "Innovation City Cape Town",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-ai-can-help-humans-find-common-ground-in-democ",
  },
  {
    id: 37,
    name: "Reading Group: Fair Algorithms for Selecting Citizens' Assemblies",
    type: "reading_group",
    eventDate: "2025-11-19",
    location: "Innovation City Cape Town",
    attendanceCount: 2,
    image: null,
    slug: "reading-group-fair-algorithms-for-selecting-citizens-assembl",
  },
  {
    id: 38,
    name: "Reading Group: Weak-to-Strong Generalization under Distribution Shifts",
    type: "reading_group",
    eventDate: "2025-11-12",
    location: "Innovation City Cape Town",
    attendanceCount: 2,
    image: null,
    slug: "reading-group-weak-to-strong-generalization-under-distributi",
  },
  {
    id: 39,
    name: "Reading Group: Collective Intelligence as Infrastructure",
    type: "reading_group",
    eventDate: "2025-11-05",
    location: "Innovation City Cape Town",
    attendanceCount: 3,
    image: null,
    slug: "reading-group-collective-intelligence-as-infrastructure",
  },
  {
    id: 40,
    name: "\u26a1Lightning Talks",
    type: "talk",
    eventDate: "2025-10-30",
    location: "Innovation City Cape Town",
    attendanceCount: 10,
    image: null,
    slug: "lightning-talks",
  },
  {
    id: 41,
    name: "Reading Group: A Definition of AGI",
    type: "reading_group",
    eventDate: "2025-10-29",
    location: "Innovation City Cape Town",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-a-definition-of-agi",
  },
  {
    id: 42,
    name: "Post-Course Social \ud83c\udf89 (Pretoria)",
    type: "meetup",
    eventDate: "2025-10-25",
    location: "Felo Restaurant Hatfield",
    attendanceCount: 4,
    image: null,
    slug: "post-course-social-pretoria",
  },
  {
    id: 43,
    name: "Post-Course Social \ud83c\udf89 (Cape Town)",
    type: "meetup",
    eventDate: "2025-10-25",
    location: "Newport Market & Deli",
    attendanceCount: 7,
    image: null,
    slug: "post-course-social-cape-town",
  },
  {
    id: 44,
    name: "Post-Course Social \ud83c\udf89 (JHB)",
    type: "meetup",
    eventDate: "2025-10-25",
    location: "Mugg & Bean Rosebank Mall",
    attendanceCount: 9,
    image: null,
    slug: "post-course-social-jhb",
  },
  {
    id: 45,
    name: "Reading Group: If Anyone Builds It, Everyone Dies",
    type: "reading_group",
    eventDate: "2025-10-22",
    location: "Innovation City Cape Town",
    attendanceCount: 11,
    image: null,
    slug: "reading-group-if-anyone-builds-it-everyone-dies",
  },
  {
    id: 46,
    name: "Reading Group: Toward an African Agenda for AI Safety",
    type: "reading_group",
    eventDate: "2025-10-15",
    location: "Innovation City Cape Town",
    attendanceCount: 2,
    image: null,
    slug: "reading-group-toward-an-african-agenda-for-ai-safety",
  },
  {
    id: 47,
    name: "Reading Group: Underwriting Superintelligence",
    type: "reading_group",
    eventDate: "2025-10-08",
    location: "Innovation City Cape Town",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-underwriting-superintelligence",
  },
  {
    id: 48,
    name: "ACX Goes Climbing",
    type: "meetup",
    eventDate: "2025-10-05",
    location: "CityROCK Cape Town - Indoor Climbing Gym",
    attendanceCount: 5,
    image: null,
    slug: "acx-goes-climbing",
  },
  {
    id: 49,
    name: "Reading Group: Why Language Models Hallucinate",
    type: "reading_group",
    eventDate: "2025-10-01",
    location: "Innovation City Cape Town",
    attendanceCount: 10,
    image: null,
    slug: "reading-group-why-language-models-hallucinate",
  },
  {
    id: 50,
    name: "AI & the future of jobs...",
    type: "other",
    eventDate: "2025-09-30",
    location: "Simonsberg Men's Residence",
    attendanceCount: 17,
    image: null,
    slug: "ai-the-future-of-jobs",
  },
  {
    id: 51,
    name: "Apply With Me: Cooperative AI Research Fellowship",
    type: "other",
    eventDate: "2025-09-27",
    location: "Google Meet",
    attendanceCount: 41,
    image: null,
    slug: "apply-with-me-cooperative-ai-research-fellowship",
  },
  {
    id: 52,
    name: "Project Day",
    type: "other",
    eventDate: "2025-09-27",
    location: "Innovation City Cape Town",
    attendanceCount: 10,
    image: null,
    slug: "project-day",
  },
  {
    id: 53,
    name: "Office Hours: AI Safety Programs (AISSA)",
    type: "other",
    eventDate: "2025-09-26",
    location: "Google Meet",
    attendanceCount: 5,
    image: null,
    slug: "office-hours-ai-safety-programs-aissa",
  },
  {
    id: 54,
    name: "Apply With Me: Cooperative AI Research Fellowship",
    type: "other",
    eventDate: "2025-09-22",
    location: "Google Meet",
    attendanceCount: 63,
    image: null,
    slug: "apply-with-me-cooperative-ai-research-fellowship-2",
  },
  {
    id: 55,
    name: "ACX Everywhere Meetup",
    type: "meetup",
    eventDate: "2025-09-21",
    location: "The Gardeners Cottage Restaurant",
    attendanceCount: 4,
    image: null,
    slug: "acx-everywhere-meetup",
  },
  {
    id: 56,
    name: "Cooperative AI Research Fellowship Info Session",
    type: "other",
    eventDate: "2025-09-18",
    location: "Zoom",
    attendanceCount: 483,
    image: null,
    slug: "cooperative-ai-research-fellowship-info-session",
  },
  {
    id: 57,
    name: "Reading Group: On the Biology of a Large Language Model",
    type: "reading_group",
    eventDate: "2025-09-17",
    location: "Innovation City Cape Town",
    attendanceCount: 5,
    image: null,
    slug: "reading-group-on-the-biology-of-a-large-language-model",
  },
  {
    id: 58,
    name: "Writing Meetup",
    type: "meetup",
    eventDate: "2025-09-13",
    location: "Innovation City Cape Town",
    attendanceCount: 4,
    image: null,
    slug: "writing-meetup",
  },
  {
    id: 59,
    name: "AI Safety South Africa Community Networking (Virtual)",
    type: "other",
    eventDate: "2025-09-11",
    location: "Google Meet",
    attendanceCount: 13,
    image: null,
    slug: "ai-safety-south-africa-community-networking-virtual",
  },
  {
    id: 60,
    name: "ACX/SSC Meetup",
    type: "meetup",
    eventDate: "2025-09-02",
    location: "Our Local Kloof Street",
    attendanceCount: 2,
    image: null,
    slug: "acx-ssc-meetup",
  },
  {
    id: 61,
    name: "Writing Meetup",
    type: "meetup",
    eventDate: "2025-08-30",
    location: "Innovation City Cape Town",
    attendanceCount: 4,
    image: null,
    slug: "writing-meetup-2",
  },
  {
    id: 62,
    name: "\u26a1Lightning Talks",
    type: "talk",
    eventDate: "2025-08-28",
    location: "Innovation City Cape Town",
    attendanceCount: 13,
    image: null,
    slug: "lightning-talks-2",
  },
  {
    id: 63,
    name: "Project Day",
    type: "other",
    eventDate: "2025-08-16",
    location: "Innovation City Cape Town",
    attendanceCount: 9,
    image: null,
    slug: "project-day-2",
  },
  {
    id: 64,
    name: "Movie Night",
    type: "other",
    eventDate: "2025-08-13",
    location: "Innovation City Cape Town",
    attendanceCount: 14,
    image: null,
    slug: "movie-night",
  },
  {
    id: 65,
    name: "\u26a1Lightning Talks",
    type: "talk",
    eventDate: "2025-07-31",
    location: "Innovation City Cape Town",
    attendanceCount: 13,
    image: null,
    slug: "lightning-talks-3",
  },
  {
    id: 66,
    name: "AISSA x Apart Research Sprint",
    type: "other",
    eventDate: "2025-07-25",
    location: "Innovation City Cape Town",
    attendanceCount: 5,
    image: null,
    slug: "aissa-x-apart-research-sprint",
  },
  {
    id: 67,
    name: "DLIX 2025 Workshop",
    type: "other",
    eventDate: "2025-07-08",
    location: "Stellenbosch University",
    attendanceCount: 20,
    image: null,
    slug: "dlix-2025-workshop",
  },
  {
    id: 68,
    name: "AI Safety Course Meet & Greet: JHB",
    type: "meetup",
    eventDate: "2025-07-07",
    location: "Randburg, Gauteng",
    attendanceCount: 14,
    image: null,
    slug: "ai-safety-course-meet-greet-jhb",
  },
  {
    id: 69,
    name: "AI Safety Course Meet & Greet: CT",
    type: "meetup",
    eventDate: "2025-07-05",
    location: "Col'Cacchio Foreshore",
    attendanceCount: 9,
    image: null,
    slug: "ai-safety-course-meet-greet-ct",
  },
  {
    id: 70,
    name: "AI Safety Course Meet & Greet: PTA",
    type: "meetup",
    eventDate: "2025-07-05",
    location: "Pretoria, Gauteng",
    attendanceCount: 6,
    image: null,
    slug: "ai-safety-course-meet-greet-pta",
  },
  {
    id: 71,
    name: "Writing Meetup",
    type: "meetup",
    eventDate: "2025-07-05",
    location: "Innovation City Cape Town",
    attendanceCount: 4,
    image: null,
    slug: "writing-meetup-3",
  },
  {
    id: 72,
    name: "Writing Meetup",
    type: "meetup",
    eventDate: "2025-07-03",
    location: "Innovation City Cape Town",
    attendanceCount: 2,
    image: null,
    slug: "writing-meetup-4",
  },
  {
    id: 73,
    name: "\u26a1Lightning Talks",
    type: "talk",
    eventDate: "2025-06-26",
    location: "Innovation City Cape Town",
    attendanceCount: 7,
    image: null,
    slug: "lightning-talks-4",
  },
  {
    id: 74,
    name: "Writer's Meetup",
    type: "meetup",
    eventDate: "2025-06-21",
    location: "Innovation City Cape Town",
    attendanceCount: 1,
    image: null,
    slug: "writer-s-meetup",
  },
  {
    id: 75,
    name: "\u26a1Lightning Talks",
    type: "talk",
    eventDate: "2025-05-22",
    location: "Innovation City Cape Town",
    attendanceCount: 8,
    image: null,
    slug: "lightning-talks-5",
  },
  {
    id: 76,
    name: "Writer's Meetup",
    type: "meetup",
    eventDate: "2025-05-19",
    location: "Innovation City Cape Town",
    attendanceCount: 2,
    image: null,
    slug: "writer-s-meetup-2",
  },
  {
    id: 77,
    name: "Community Meetup: Astral Codex Ten (ACX)",
    type: "meetup",
    eventDate: "2025-05-08",
    location: "Tiger's Milk Kloof Street",
    attendanceCount: 14,
    image: null,
    slug: "community-meetup-astral-codex-ten-acx",
  },
  {
    id: 78,
    name: "Writer's Meetup",
    type: "meetup",
    eventDate: "2025-05-01",
    location: "Innovation City Cape Town",
    attendanceCount: 4,
    image: null,
    slug: "writer-s-meetup-3",
  },
  {
    id: 79,
    name: "Reading Group: Auditing Misaligned Models",
    type: "reading_group",
    eventDate: "2025-03-26",
    location: "Innovation City Cape Town",
    attendanceCount: 8,
    image: null,
    slug: "reading-group-auditing-misaligned-models",
  },
  {
    id: 80,
    name: "Reading Group: Superintelligence Strategy",
    type: "reading_group",
    eventDate: "2025-03-19",
    location: "Innovation City Cape Town",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-superintelligence-strategy",
  },
  {
    id: 81,
    name: "Community Update: Shifting Landscapes & Evaluating AI Agents",
    type: "talk",
    eventDate: "2025-03-12",
    location: "Innovation City Cape Town",
    attendanceCount: 15,
    image: null,
    slug: "community-update-shifting-landscapes-evaluating-ai-agents",
  },
  {
    id: 82,
    name: "Reading Group: Model Organisms of Misalignment",
    type: "reading_group",
    eventDate: "2025-02-26",
    location: "Innovation City Cape Town",
    attendanceCount: 4,
    image: null,
    slug: "reading-group-model-organisms-of-misalignment",
  },
  {
    id: 83,
    name: "Reading Group: Cooperative AI",
    type: "reading_group",
    eventDate: "2025-02-19",
    location: "Innovation City Cape Town",
    attendanceCount: 3,
    image: null,
    slug: "reading-group-cooperative-ai",
  },
  {
    id: 84,
    name: "Stellies AI Safety - First Meetup",
    type: "meetup",
    eventDate: "2025-02-05",
    location: "stellenbosch_university",
    attendanceCount: 12,
    image: null,
    slug: "stellies-ai-safety-first-meetup",
  },
  {
    id: 85,
    name: "Reading Group: DeepSeek-R1 and its Implications",
    type: "reading_group",
    eventDate: "2025-02-05",
    location: "Innovation City Cape Town",
    attendanceCount: 9,
    image: null,
    slug: "reading-group-deepseek-r1-and-its-implications",
  },
  {
    id: 86,
    name: "AI Safety WITS - First Meetup",
    type: "meetup",
    eventDate: "2025-02-01",
    location: "wits_university",
    attendanceCount: 23,
    image: null,
    slug: "ai-safety-wits-first-meetup",
  },
  {
    id: 87,
    name: "Reading Group: AI Governance",
    type: "reading_group",
    eventDate: "2025-01-29",
    location: "Innovation City Cape Town",
    attendanceCount: 9,
    image: null,
    slug: "reading-group-ai-governance",
  },
  {
    id: 88,
    name: "AI Governance Faculty Meetup Early 2025",
    type: "meetup",
    eventDate: "2025-01-20",
    location: "cape_town",
    attendanceCount: 6,
    image: null,
    slug: "ai-governance-faculty-meetup-early-2025",
  },
  {
    id: 89,
    name: "Cooperative AI Talk and Discussion",
    type: "talk",
    eventDate: "2025-01-15",
    location: "innovation_city",
    attendanceCount: 20,
    image: null,
    slug: "cooperative-ai-talk-and-discussion",
  },
  {
    id: 90,
    name: "Deep Learning IndabaX (July 2024): An Introduction to AI-Risk, Key Concepts in AI Safety",
    type: "workshop",
    eventDate: "2024-07-15",
    location: "indabax_venue",
    attendanceCount: 50,
    image: null,
    slug: "deep-learning-indabax-july-2024-an-introduction-to-ai-risk-k",
  },
  {
    id: 91,
    name: "Deep Learning IndabaX (July 2024): AGI Horizons: Utopia, Dystopia, and Everything in-Between",
    type: "panel",
    eventDate: "2024-07-15",
    location: "indabax_venue",
    attendanceCount: 125,
    image: null,
    slug: "deep-learning-indabax-july-2024-agi-horizons-utopia-dystopia",
  },
  {
    id: 92,
    name: "EA South Africa x AI Safety Cape Town (May 2024): AI Safety Virtual Workshop (Pilot)",
    type: "workshop",
    eventDate: "2024-05-15",
    location: "online",
    attendanceCount: 10,
    image: null,
    slug: "ea-south-africa-x-ai-safety-cape-town-may-2024-ai-safety-vir",
  },
  {
    id: 93,
    name: "IndabaXS (March 2024): AI Safety Roundtable",
    type: "workshop",
    eventDate: "2024-03-20",
    location: "indabaxs_venue",
    attendanceCount: 15,
    image: null,
    slug: "indabaxs-march-2024-ai-safety-roundtable",
  },
  {
    id: 94,
    name: "EASA Summit",
    type: "other",
    eventDate: "2024-01-01",
    location: "TBD",
    attendanceCount: null,
    image: null,
    slug: "easa-summit",
  },
  {
    id: 95,
    name: "G20 Side Event: AI Governance Panel",
    type: "panel",
    eventDate: "2024-01-01",
    location: "Harvard Africa Office, Johannesburg",
    attendanceCount: null,
    image: null,
    slug: "g20-side-event-ai-governance-panel",
  },
  {
    id: 96,
    name: "SACAIR (November 2023): AI Safety Tutorial",
    type: "workshop",
    eventDate: "2023-11-15",
    location: "sacair_venue",
    attendanceCount: 30,
    image: null,
    slug: "sacair-november-2023-ai-safety-tutorial",
  },
  {
    id: 97,
    name: "IndabaXS: AI Risk and Opportunity in Africa",
    type: "workshop",
    eventDate: "2023-08-10",
    location: "indabaxs_venue",
    attendanceCount: 15,
    image: null,
    slug: "indabaxs-ai-risk-and-opportunity-in-africa",
  },
  {
    id: 98,
    name: "Deep Learning IndabaX (July 2023): AI Safety and Governance Workshop",
    type: "workshop",
    eventDate: "2023-07-20",
    location: "indabax_venue",
    attendanceCount: 40,
    image: null,
    slug: "deep-learning-indabax-july-2023-ai-safety-and-governance-wor",
  },
];
