/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_organisations_type = pgEnum('enum_organisations_type', [
  'university',
  'corporate',
  'nonprofit',
  'government',
])
export const enum_partnerships_type = pgEnum('enum_partnerships_type', [
  'venue',
  'funding',
  'collaboration',
  'media',
])
export const enum_programs_type = pgEnum('enum_programs_type', [
  'fellowship',
  'course',
  'coworking',
  'volunteer_program',
])
export const enum_events_type = pgEnum('enum_events_type', [
  'workshop',
  'talk',
  'meetup',
  'reading_group',
  'retreat',
  'panel',
])
export const enum_projects_type = pgEnum('enum_projects_type', [
  'research_paper',
  'bounty_submission',
  'grant_award',
  'software_tool',
])
export const enum_projects_project_status = pgEnum('enum_projects_project_status', [
  'in_progress',
  'submitted',
  'accepted',
  'published',
])
export const enum_project_contributors_role = pgEnum('enum_project_contributors_role', [
  'lead_author',
  'co_author',
  'contributor',
  'advisor',
])
export const enum_engagements_type = pgEnum('enum_engagements_type', [
  'participant',
  'facilitator',
  'speaker',
  'volunteer',
  'organizer',
  'mentor',
])
export const enum_engagements_engagement_status = pgEnum('enum_engagements_engagement_status', [
  'completed',
  'dropped_out',
  'in_progress',
  'withdrawn',
  'attended',
])
export const enum_engagement_impacts_type = pgEnum('enum_engagement_impacts_type', [
  'career_transition',
  'research_contribution',
  'community_building',
  'grant_awarded',
  'publication',
  'educational',
  'community',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const persons = pgTable(
  'persons',
  {
    id: serial('id').primaryKey(),
    email: varchar('email').notNull(),
    fullName: varchar('full_name').notNull(),
    preferredName: varchar('preferred_name'),
    bio: varchar('bio'),
    websiteUrl: varchar('website_url'),
    headshot: integer('headshot_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    joinedAt: timestamp('joined_at', { mode: 'string', withTimezone: true, precision: 3 }),
    isPublished: boolean('is_published').default(false),
    highlight: boolean('highlight').default(false),
    featuredStory: jsonb('featured_story'),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('persons_email_idx').on(columns.email),
    index('persons_headshot_idx').on(columns.headshot),
    index('persons_updated_at_idx').on(columns.updatedAt),
    index('persons_created_at_idx').on(columns.createdAt),
  ],
)

export const organisations = pgTable(
  'organisations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    type: enum_organisations_type('type'),
    website: varchar('website'),
    description: varchar('description'),
    isPartnershipActive: boolean('is_partnership_active').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('organisations_updated_at_idx').on(columns.updatedAt),
    index('organisations_created_at_idx').on(columns.createdAt),
  ],
)

export const partnerships = pgTable(
  'partnerships',
  {
    id: serial('id').primaryKey(),
    organisation: integer('organisation_id')
      .notNull()
      .references(() => organisations.id, {
        onDelete: 'set null',
      }),
    type: enum_partnerships_type('type').notNull(),
    description: varchar('description'),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('partnerships_organisation_idx').on(columns.organisation),
    index('partnerships_updated_at_idx').on(columns.updatedAt),
    index('partnerships_created_at_idx').on(columns.createdAt),
  ],
)

export const programs = pgTable(
  'programs',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    name: varchar('name').notNull(),
    type: enum_programs_type('type').notNull(),
    partnership: integer('partnership_id').references(() => partnerships.id, {
      onDelete: 'set null',
    }),
    description: jsonb('description'),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('programs_slug_idx').on(columns.slug),
    index('programs_partnership_idx').on(columns.partnership),
    index('programs_updated_at_idx').on(columns.updatedAt),
    index('programs_created_at_idx').on(columns.createdAt),
  ],
)

export const cohorts = pgTable(
  'cohorts',
  {
    id: serial('id').primaryKey(),
    program: integer('program_id')
      .notNull()
      .references(() => programs.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    applicationCount: numeric('application_count', { mode: 'number' }),
    acceptedCount: numeric('accepted_count', { mode: 'number' }),
    completionCount: numeric('completion_count', { mode: 'number' }),
    completionRate: numeric('completion_rate', { mode: 'number' }),
    averageRating: numeric('average_rating', { mode: 'number' }),
    dropoutRate: numeric('dropout_rate', { mode: 'number' }),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('cohorts_program_idx').on(columns.program),
    uniqueIndex('cohorts_slug_idx').on(columns.slug),
    index('cohorts_updated_at_idx').on(columns.updatedAt),
    index('cohorts_created_at_idx').on(columns.createdAt),
  ],
)

export const events = pgTable(
  'events',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    name: varchar('name').notNull(),
    type: enum_events_type('type').notNull(),
    organiser: integer('organiser_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    eventDate: timestamp('event_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    attendanceCount: numeric('attendance_count', { mode: 'number' }),
    location: varchar('location'),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('events_slug_idx').on(columns.slug),
    index('events_organiser_idx').on(columns.organiser),
    index('events_updated_at_idx').on(columns.updatedAt),
    index('events_created_at_idx').on(columns.createdAt),
  ],
)

export const projects = pgTable(
  'projects',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    title: varchar('title').notNull(),
    type: enum_projects_type('type').notNull(),
    project_status: enum_projects_project_status('project_status').default('in_progress'),
    program: integer('program_id').references(() => programs.id, {
      onDelete: 'set null',
    }),
    linkUrl: varchar('link_url'),
    repositoryUrl: varchar('repository_url'),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('projects_slug_idx').on(columns.slug),
    index('projects_program_idx').on(columns.program),
    index('projects_updated_at_idx').on(columns.updatedAt),
    index('projects_created_at_idx').on(columns.createdAt),
  ],
)

export const event_hosts = pgTable(
  'event_hosts',
  {
    id: serial('id').primaryKey(),
    event: integer('event_id')
      .notNull()
      .references(() => events.id, {
        onDelete: 'set null',
      }),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('event_hosts_event_idx').on(columns.event),
    index('event_hosts_person_idx').on(columns.person),
    index('event_hosts_updated_at_idx').on(columns.updatedAt),
    index('event_hosts_created_at_idx').on(columns.createdAt),
  ],
)

export const project_contributors = pgTable(
  'project_contributors',
  {
    id: serial('id').primaryKey(),
    project: integer('project_id')
      .notNull()
      .references(() => projects.id, {
        onDelete: 'set null',
      }),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    role: enum_project_contributors_role('role').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('project_contributors_project_idx').on(columns.project),
    index('project_contributors_person_idx').on(columns.person),
    index('project_contributors_updated_at_idx').on(columns.updatedAt),
    index('project_contributors_created_at_idx').on(columns.createdAt),
  ],
)

export const engagements = pgTable(
  'engagements',
  {
    id: serial('id').primaryKey(),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    type: enum_engagements_type('type').notNull(),
    event: integer('event_id').references(() => events.id, {
      onDelete: 'set null',
    }),
    program: integer('program_id').references(() => programs.id, {
      onDelete: 'set null',
    }),
    cohort: integer('cohort_id').references(() => cohorts.id, {
      onDelete: 'set null',
    }),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    rating: numeric('rating', { mode: 'number' }),
    wouldRecommend: numeric('would_recommend', { mode: 'number' }),
    engagement_status: enum_engagements_engagement_status('engagement_status'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('engagements_person_idx').on(columns.person),
    index('engagements_event_idx').on(columns.event),
    index('engagements_program_idx').on(columns.program),
    index('engagements_cohort_idx').on(columns.cohort),
    index('engagements_updated_at_idx').on(columns.updatedAt),
    index('engagements_created_at_idx').on(columns.createdAt),
  ],
)

export const engagement_impacts = pgTable(
  'engagement_impacts',
  {
    id: serial('id').primaryKey(),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    engagement: integer('engagement_id').references(() => engagements.id, {
      onDelete: 'set null',
    }),
    affiliatedOrganisation: integer('affiliated_organisation_id').references(
      () => organisations.id,
      {
        onDelete: 'set null',
      },
    ),
    type: enum_engagement_impacts_type('type').notNull(),
    summary: varchar('summary').notNull(),
    evidenceUrl: varchar('evidence_url'),
    isVerified: boolean('is_verified').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('engagement_impacts_person_idx').on(columns.person),
    index('engagement_impacts_engagement_idx').on(columns.engagement),
    index('engagement_impacts_affiliated_organisation_idx').on(columns.affiliatedOrganisation),
    index('engagement_impacts_updated_at_idx').on(columns.updatedAt),
    index('engagement_impacts_created_at_idx').on(columns.createdAt),
  ],
)

export const testimonials = pgTable(
  'testimonials',
  {
    id: serial('id').primaryKey(),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    program: integer('program_id').references(() => programs.id, {
      onDelete: 'set null',
    }),
    event: integer('event_id').references(() => events.id, {
      onDelete: 'set null',
    }),
    cohort: integer('cohort_id').references(() => cohorts.id, {
      onDelete: 'set null',
    }),
    quote: varchar('quote').notNull(),
    attributionName: varchar('attribution_name'),
    attributionTitle: varchar('attribution_title'),
    rating: numeric('rating', { mode: 'number' }),
    isPublished: boolean('is_published').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('testimonials_person_idx').on(columns.person),
    index('testimonials_program_idx').on(columns.program),
    index('testimonials_event_idx').on(columns.event),
    index('testimonials_cohort_idx').on(columns.cohort),
    index('testimonials_updated_at_idx').on(columns.updatedAt),
    index('testimonials_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    personsID: integer('persons_id'),
    organisationsID: integer('organisations_id'),
    partnershipsID: integer('partnerships_id'),
    programsID: integer('programs_id'),
    cohortsID: integer('cohorts_id'),
    eventsID: integer('events_id'),
    projectsID: integer('projects_id'),
    'event-hostsID': integer('event_hosts_id'),
    'project-contributorsID': integer('project_contributors_id'),
    engagementsID: integer('engagements_id'),
    'engagement-impactsID': integer('engagement_impacts_id'),
    testimonialsID: integer('testimonials_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_persons_id_idx').on(columns.personsID),
    index('payload_locked_documents_rels_organisations_id_idx').on(columns.organisationsID),
    index('payload_locked_documents_rels_partnerships_id_idx').on(columns.partnershipsID),
    index('payload_locked_documents_rels_programs_id_idx').on(columns.programsID),
    index('payload_locked_documents_rels_cohorts_id_idx').on(columns.cohortsID),
    index('payload_locked_documents_rels_events_id_idx').on(columns.eventsID),
    index('payload_locked_documents_rels_projects_id_idx').on(columns.projectsID),
    index('payload_locked_documents_rels_event_hosts_id_idx').on(columns['event-hostsID']),
    index('payload_locked_documents_rels_project_contributors_id_idx').on(
      columns['project-contributorsID'],
    ),
    index('payload_locked_documents_rels_engagements_id_idx').on(columns.engagementsID),
    index('payload_locked_documents_rels_engagement_impacts_id_idx').on(
      columns['engagement-impactsID'],
    ),
    index('payload_locked_documents_rels_testimonials_id_idx').on(columns.testimonialsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['personsID']],
      foreignColumns: [persons.id],
      name: 'payload_locked_documents_rels_persons_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['organisationsID']],
      foreignColumns: [organisations.id],
      name: 'payload_locked_documents_rels_organisations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partnershipsID']],
      foreignColumns: [partnerships.id],
      name: 'payload_locked_documents_rels_partnerships_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'payload_locked_documents_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cohortsID']],
      foreignColumns: [cohorts.id],
      name: 'payload_locked_documents_rels_cohorts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'payload_locked_documents_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'payload_locked_documents_rels_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['event-hostsID']],
      foreignColumns: [event_hosts.id],
      name: 'payload_locked_documents_rels_event_hosts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['project-contributorsID']],
      foreignColumns: [project_contributors.id],
      name: 'payload_locked_documents_rels_project_contributors_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['engagementsID']],
      foreignColumns: [engagements.id],
      name: 'payload_locked_documents_rels_engagements_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['engagement-impactsID']],
      foreignColumns: [engagement_impacts.id],
      name: 'payload_locked_documents_rels_engagement_impacts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'payload_locked_documents_rels_testimonials_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_persons = relations(persons, ({ one }) => ({
  headshot: one(media, {
    fields: [persons.headshot],
    references: [media.id],
    relationName: 'headshot',
  }),
}))
export const relations_organisations = relations(organisations, () => ({}))
export const relations_partnerships = relations(partnerships, ({ one }) => ({
  organisation: one(organisations, {
    fields: [partnerships.organisation],
    references: [organisations.id],
    relationName: 'organisation',
  }),
}))
export const relations_programs = relations(programs, ({ one }) => ({
  partnership: one(partnerships, {
    fields: [programs.partnership],
    references: [partnerships.id],
    relationName: 'partnership',
  }),
}))
export const relations_cohorts = relations(cohorts, ({ one }) => ({
  program: one(programs, {
    fields: [cohorts.program],
    references: [programs.id],
    relationName: 'program',
  }),
}))
export const relations_events = relations(events, ({ one }) => ({
  organiser: one(persons, {
    fields: [events.organiser],
    references: [persons.id],
    relationName: 'organiser',
  }),
}))
export const relations_projects = relations(projects, ({ one }) => ({
  program: one(programs, {
    fields: [projects.program],
    references: [programs.id],
    relationName: 'program',
  }),
}))
export const relations_event_hosts = relations(event_hosts, ({ one }) => ({
  event: one(events, {
    fields: [event_hosts.event],
    references: [events.id],
    relationName: 'event',
  }),
  person: one(persons, {
    fields: [event_hosts.person],
    references: [persons.id],
    relationName: 'person',
  }),
}))
export const relations_project_contributors = relations(project_contributors, ({ one }) => ({
  project: one(projects, {
    fields: [project_contributors.project],
    references: [projects.id],
    relationName: 'project',
  }),
  person: one(persons, {
    fields: [project_contributors.person],
    references: [persons.id],
    relationName: 'person',
  }),
}))
export const relations_engagements = relations(engagements, ({ one }) => ({
  person: one(persons, {
    fields: [engagements.person],
    references: [persons.id],
    relationName: 'person',
  }),
  event: one(events, {
    fields: [engagements.event],
    references: [events.id],
    relationName: 'event',
  }),
  program: one(programs, {
    fields: [engagements.program],
    references: [programs.id],
    relationName: 'program',
  }),
  cohort: one(cohorts, {
    fields: [engagements.cohort],
    references: [cohorts.id],
    relationName: 'cohort',
  }),
}))
export const relations_engagement_impacts = relations(engagement_impacts, ({ one }) => ({
  person: one(persons, {
    fields: [engagement_impacts.person],
    references: [persons.id],
    relationName: 'person',
  }),
  engagement: one(engagements, {
    fields: [engagement_impacts.engagement],
    references: [engagements.id],
    relationName: 'engagement',
  }),
  affiliatedOrganisation: one(organisations, {
    fields: [engagement_impacts.affiliatedOrganisation],
    references: [organisations.id],
    relationName: 'affiliatedOrganisation',
  }),
}))
export const relations_testimonials = relations(testimonials, ({ one }) => ({
  person: one(persons, {
    fields: [testimonials.person],
    references: [persons.id],
    relationName: 'person',
  }),
  program: one(programs, {
    fields: [testimonials.program],
    references: [programs.id],
    relationName: 'program',
  }),
  event: one(events, {
    fields: [testimonials.event],
    references: [events.id],
    relationName: 'event',
  }),
  cohort: one(cohorts, {
    fields: [testimonials.cohort],
    references: [cohorts.id],
    relationName: 'cohort',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    personsID: one(persons, {
      fields: [payload_locked_documents_rels.personsID],
      references: [persons.id],
      relationName: 'persons',
    }),
    organisationsID: one(organisations, {
      fields: [payload_locked_documents_rels.organisationsID],
      references: [organisations.id],
      relationName: 'organisations',
    }),
    partnershipsID: one(partnerships, {
      fields: [payload_locked_documents_rels.partnershipsID],
      references: [partnerships.id],
      relationName: 'partnerships',
    }),
    programsID: one(programs, {
      fields: [payload_locked_documents_rels.programsID],
      references: [programs.id],
      relationName: 'programs',
    }),
    cohortsID: one(cohorts, {
      fields: [payload_locked_documents_rels.cohortsID],
      references: [cohorts.id],
      relationName: 'cohorts',
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: 'events',
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: 'projects',
    }),
    'event-hostsID': one(event_hosts, {
      fields: [payload_locked_documents_rels['event-hostsID']],
      references: [event_hosts.id],
      relationName: 'event-hosts',
    }),
    'project-contributorsID': one(project_contributors, {
      fields: [payload_locked_documents_rels['project-contributorsID']],
      references: [project_contributors.id],
      relationName: 'project-contributors',
    }),
    engagementsID: one(engagements, {
      fields: [payload_locked_documents_rels.engagementsID],
      references: [engagements.id],
      relationName: 'engagements',
    }),
    'engagement-impactsID': one(engagement_impacts, {
      fields: [payload_locked_documents_rels['engagement-impactsID']],
      references: [engagement_impacts.id],
      relationName: 'engagement-impacts',
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: 'testimonials',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_organisations_type: typeof enum_organisations_type
  enum_partnerships_type: typeof enum_partnerships_type
  enum_programs_type: typeof enum_programs_type
  enum_events_type: typeof enum_events_type
  enum_projects_type: typeof enum_projects_type
  enum_projects_project_status: typeof enum_projects_project_status
  enum_project_contributors_role: typeof enum_project_contributors_role
  enum_engagements_type: typeof enum_engagements_type
  enum_engagements_engagement_status: typeof enum_engagements_engagement_status
  enum_engagement_impacts_type: typeof enum_engagement_impacts_type
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  persons: typeof persons
  organisations: typeof organisations
  partnerships: typeof partnerships
  programs: typeof programs
  cohorts: typeof cohorts
  events: typeof events
  projects: typeof projects
  event_hosts: typeof event_hosts
  project_contributors: typeof project_contributors
  engagements: typeof engagements
  engagement_impacts: typeof engagement_impacts
  testimonials: typeof testimonials
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_persons: typeof relations_persons
  relations_organisations: typeof relations_organisations
  relations_partnerships: typeof relations_partnerships
  relations_programs: typeof relations_programs
  relations_cohorts: typeof relations_cohorts
  relations_events: typeof relations_events
  relations_projects: typeof relations_projects
  relations_event_hosts: typeof relations_event_hosts
  relations_project_contributors: typeof relations_project_contributors
  relations_engagements: typeof relations_engagements
  relations_engagement_impacts: typeof relations_engagement_impacts
  relations_testimonials: typeof relations_testimonials
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
