/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  integer,
  varchar,
  boolean,
  timestamp,
  jsonb,
  numeric,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_community_submissions_status = pgEnum('enum_community_submissions_status', [
  'draft',
  'pending_verification',
  'pending_review',
  'approved',
  'rejected',
  'partial',
])
export const enum_staged_person_updates_field = pgEnum('enum_staged_person_updates_field', [
  'fullName',
  'preferredName',
  'personTag',
  'bio',
  'websiteUrl',
  'organisation',
  'headshot',
])
export const enum_staged_person_updates_review_status = pgEnum(
  'enum_staged_person_updates_review_status',
  ['pending', 'approved', 'rejected'],
)
export const enum_staged_engagements_context_kind = pgEnum('enum_staged_engagements_context_kind', [
  'event',
  'program',
])
export const enum_staged_engagements_type = pgEnum('enum_staged_engagements_type', [
  'participant',
  'facilitator',
  'speaker',
  'volunteer',
  'organizer',
  'mentor',
  'other',
])
export const enum_staged_engagements_engagement_status = pgEnum(
  'enum_staged_engagements_engagement_status',
  ['completed', 'dropped_out', 'in_progress', 'withdrawn', 'attended'],
)
export const enum_staged_engagements_operation = pgEnum('enum_staged_engagements_operation', [
  'create',
  'update',
])
export const enum_staged_engagements_review_status = pgEnum(
  'enum_staged_engagements_review_status',
  ['pending', 'approved', 'rejected'],
)
export const enum_staged_engagement_removals_review_status = pgEnum(
  'enum_staged_engagement_removals_review_status',
  ['pending', 'approved', 'rejected'],
)
export const enum_staged_testimonials_context_kind = pgEnum(
  'enum_staged_testimonials_context_kind',
  ['event', 'program'],
)
export const enum_staged_testimonials_review_status = pgEnum(
  'enum_staged_testimonials_review_status',
  ['pending', 'approved', 'rejected'],
)
export const enum_staged_engagement_impacts_context_kind = pgEnum(
  'enum_staged_engagement_impacts_context_kind',
  ['event', 'program'],
)
export const enum_staged_engagement_impacts_type = pgEnum('enum_staged_engagement_impacts_type', [
  'career_transition',
  'research_contribution',
  'community_building',
  'grant_awarded',
  'publication',
  'educational',
  'community',
  'other',
])
export const enum_staged_engagement_impacts_action_category = pgEnum(
  'enum_staged_engagement_impacts_action_category',
  [
    'career_role',
    'grant',
    'internship',
    'academic_pivot',
    'upskilling',
    'community_building',
    'research',
  ],
)
export const enum_staged_engagement_impacts_review_status = pgEnum(
  'enum_staged_engagement_impacts_review_status',
  ['pending', 'approved', 'rejected'],
)
export const enum_engagements_type = pgEnum('enum_engagements_type', [
  'participant',
  'facilitator',
  'speaker',
  'volunteer',
  'organizer',
  'mentor',
  'contribution',
  'other',
])
export const enum_engagements_context_kind = pgEnum('enum_engagements_context_kind', [
  'event',
  'program',
  'cohort',
])
export const enum_engagements_engagement_status = pgEnum('enum_engagements_engagement_status', [
  'completed',
  'dropped_out',
  'in_progress',
  'withdrawn',
  'attended',
])
export const enum_engagements_outcome_career_intent = pgEnum(
  'enum_engagements_outcome_career_intent',
  ['no_change', 'considering', 'applying', 'hired'],
)
export const enum_engagements_outcome_project_status = pgEnum(
  'enum_engagements_outcome_project_status',
  ['none', 'started', 'completed'],
)
export const enum_engagements_career_impact = pgEnum('enum_engagements_career_impact', [
  'no_change',
  'considering_transition',
  'actively_transitioning',
  'transitioned',
  'enhanced_current_role',
])
export const enum_engagement_impacts_type = pgEnum('enum_engagement_impacts_type', [
  'career_transition',
  'research_contribution',
  'community_building',
  'grant_awarded',
  'publication',
  'educational',
  'community',
  'other',
])
export const enum_engagement_impacts_action_category = pgEnum(
  'enum_engagement_impacts_action_category',
  [
    'career_role',
    'grant',
    'internship',
    'academic_pivot',
    'upskilling',
    'community_building',
    'research',
  ],
)
export const enum_testimonials_context_kind = pgEnum('enum_testimonials_context_kind', [
  'event',
  'program',
  'cohort',
])
export const enum_feedback_submissions_source = pgEnum('enum_feedback_submissions_source', [
  'event_participant_feedback',
  'event_facilitator_report',
  'program_pre_survey',
  'program_post_survey',
  'other',
])
export const enum_feedback_submissions_workflow_type = pgEnum(
  'enum_feedback_submissions_workflow_type',
  [
    'event_participant_feedback',
    'event_facilitator_report',
    'program_pre_survey',
    'program_post_survey',
  ],
)
export const enum_feedback_submissions_processing_status = pgEnum(
  'enum_feedback_submissions_processing_status',
  ['pending', 'processing', 'completed', 'failed'],
)
export const enum_feedback_submissions_context_kind = pgEnum(
  'enum_feedback_submissions_context_kind',
  ['event', 'program', 'cohort'],
)
export const enum_feedback_submissions_form_type = pgEnum('enum_feedback_submissions_form_type', [
  'event_feedback',
  'program_pre',
  'program_post',
  'program_longitudinal',
  'annual',
])
export const enum_feedback_submissions_marketing_source = pgEnum(
  'enum_feedback_submissions_marketing_source',
  ['newsletter', 'linkedin', 'friend', 'university', 'other'],
)
export const enum_persons_current_impact_stage = pgEnum('enum_persons_current_impact_stage', [
  'awareness',
  'learning',
  'application',
  'contribution',
])
export const enum_external_identities_provider = pgEnum('enum_external_identities_provider', [
  'tally',
  'google_sheets',
  'manual',
  'other',
])
export const enum_organisations_type = pgEnum('enum_organisations_type', [
  'university',
  'corporate',
  'nonprofit',
  'government',
])
export const enum_partnerships_type = pgEnum('enum_partnerships_type', [
  'venue',
  'funding',
  'collaboration',
  'media',
])
export const enum_programs_type = pgEnum('enum_programs_type', [
  'fellowship',
  'course',
  'hackathon',
  'coworking',
  'volunteer_program',
  'other',
])
export const enum_events_type = pgEnum('enum_events_type', [
  'workshop',
  'talk',
  'meetup',
  'reading_group',
  'retreat',
  'panel',
  'other',
])
export const enum_projects_type = pgEnum('enum_projects_type', [
  'research_paper',
  'bounty_submission',
  'grant_award',
  'software_tool',
  'program_project',
  'other',
])
export const enum_projects_project_status = pgEnum('enum_projects_project_status', [
  'in_progress',
  'submitted',
  'accepted',
  'published',
])
export const enum_projects_tier = pgEnum('enum_projects_tier', ['gold', 'silver', 'bronze'])
export const enum_grants_currency = pgEnum('enum_grants_currency', ['USD', 'ZAR', 'EUR'])
export const enum_grants_status = pgEnum('enum_grants_status', [
  'draft',
  'applied',
  'awarded',
  'active',
  'completed',
])
export const enum_research_venue_type = pgEnum('enum_research_venue_type', [
  'journal',
  'conference',
  'workshop',
  'preprint',
])
export const enum_research_status = pgEnum('enum_research_status', [
  'draft',
  'submitted',
  'accepted',
  'published',
])
export const enum_project_contributors_role = pgEnum('enum_project_contributors_role', [
  'lead_author',
  'co_author',
  'contributor',
  'advisor',
  'other',
])
export const enum_payload_jobs_log_task_slug = pgEnum('enum_payload_jobs_log_task_slug', [
  'inline',
  'processTallySubmission',
])
export const enum_payload_jobs_log_state = pgEnum('enum_payload_jobs_log_state', [
  'failed',
  'succeeded',
])
export const enum_payload_jobs_task_slug = pgEnum('enum_payload_jobs_task_slug', [
  'inline',
  'processTallySubmission',
])

export const community_submissions = pgTable(
  'community_submissions',
  {
    id: serial('id').primaryKey(),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    email: varchar('email').notNull(),
    verifiedEmail: boolean('verified_email').default(false),
    verificationTokenHash: varchar('verification_token_hash'),
    verificationExpires: timestamp('verification_expires', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    status: enum_community_submissions_status('status').notNull().default('draft'),
    reviewedBy: integer('reviewed_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    reviewedAt: timestamp('reviewed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    reviewNotes: varchar('review_notes'),
    submittedAt: timestamp('submitted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    generalTestimonial: varchar('general_testimonial'),
    generalTestimonialConsent: boolean('general_testimonial_consent').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('community_submissions_person_idx').on(columns.person),
    index('community_submissions_email_idx').on(columns.email),
    index('community_submissions_verified_email_idx').on(columns.verifiedEmail),
    index('community_submissions_verification_token_hash_idx').on(columns.verificationTokenHash),
    index('community_submissions_verification_expires_idx').on(columns.verificationExpires),
    index('community_submissions_status_idx').on(columns.status),
    index('community_submissions_reviewed_by_idx').on(columns.reviewedBy),
    index('community_submissions_submitted_at_idx').on(columns.submittedAt),
    index('community_submissions_updated_at_idx').on(columns.updatedAt),
    index('community_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const staged_person_updates = pgTable(
  'staged_person_updates',
  {
    id: serial('id').primaryKey(),
    submission: integer('submission_id')
      .notNull()
      .references(() => community_submissions.id, {
        onDelete: 'set null',
      }),
    field: enum_staged_person_updates_field('field').notNull(),
    currentValue: jsonb('current_value'),
    proposedValue: jsonb('proposed_value').notNull(),
    reviewStatus: enum_staged_person_updates_review_status('review_status')
      .notNull()
      .default('pending'),
    reviewNotes: varchar('review_notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('staged_person_updates_submission_idx').on(columns.submission),
    index('staged_person_updates_field_idx').on(columns.field),
    index('staged_person_updates_review_status_idx').on(columns.reviewStatus),
    index('staged_person_updates_updated_at_idx').on(columns.updatedAt),
    index('staged_person_updates_created_at_idx').on(columns.createdAt),
  ],
)

export const staged_engagements = pgTable(
  'staged_engagements',
  {
    id: serial('id').primaryKey(),
    submission: integer('submission_id')
      .notNull()
      .references(() => community_submissions.id, {
        onDelete: 'set null',
      }),
    contextKind: enum_staged_engagements_context_kind('context_kind').notNull(),
    contextDate: timestamp('context_date', { mode: 'string', withTimezone: true, precision: 3 }),
    type: enum_staged_engagements_type('type').notNull(),
    typeOther: varchar('type_other'),
    engagement_status: enum_staged_engagements_engagement_status('engagement_status'),
    rating: numeric('rating', { mode: 'number' }),
    wouldRecommend: numeric('would_recommend', { mode: 'number' }),
    operation: enum_staged_engagements_operation('operation').notNull().default('create'),
    existingEngagement: integer('existing_engagement_id').references(() => engagements.id, {
      onDelete: 'set null',
    }),
    currentValue: jsonb('current_value'),
    reviewStatus: enum_staged_engagements_review_status('review_status')
      .notNull()
      .default('pending'),
    reviewNotes: varchar('review_notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('staged_engagements_submission_idx').on(columns.submission),
    index('staged_engagements_context_kind_idx').on(columns.contextKind),
    index('staged_engagements_context_date_idx').on(columns.contextDate),
    index('staged_engagements_existing_engagement_idx').on(columns.existingEngagement),
    index('staged_engagements_review_status_idx').on(columns.reviewStatus),
    index('staged_engagements_updated_at_idx').on(columns.updatedAt),
    index('staged_engagements_created_at_idx').on(columns.createdAt),
  ],
)

export const staged_engagements_rels = pgTable(
  'staged_engagements_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    eventsID: integer('events_id'),
    programsID: integer('programs_id'),
  },
  (columns) => [
    index('staged_engagements_rels_order_idx').on(columns.order),
    index('staged_engagements_rels_parent_idx').on(columns.parent),
    index('staged_engagements_rels_path_idx').on(columns.path),
    index('staged_engagements_rels_events_id_idx').on(columns.eventsID),
    index('staged_engagements_rels_programs_id_idx').on(columns.programsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [staged_engagements.id],
      name: 'staged_engagements_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'staged_engagements_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'staged_engagements_rels_programs_fk',
    }).onDelete('cascade'),
  ],
)

export const staged_engagement_removals = pgTable(
  'staged_engagement_removals',
  {
    id: serial('id').primaryKey(),
    submission: integer('submission_id')
      .notNull()
      .references(() => community_submissions.id, {
        onDelete: 'set null',
      }),
    engagement: integer('engagement_id')
      .notNull()
      .references(() => engagements.id, {
        onDelete: 'set null',
      }),
    reason: varchar('reason').notNull(),
    currentValue: jsonb('current_value'),
    reviewStatus: enum_staged_engagement_removals_review_status('review_status')
      .notNull()
      .default('pending'),
    reviewNotes: varchar('review_notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('staged_engagement_removals_submission_idx').on(columns.submission),
    index('staged_engagement_removals_engagement_idx').on(columns.engagement),
    index('staged_engagement_removals_review_status_idx').on(columns.reviewStatus),
    index('staged_engagement_removals_updated_at_idx').on(columns.updatedAt),
    index('staged_engagement_removals_created_at_idx').on(columns.createdAt),
  ],
)

export const staged_testimonials = pgTable(
  'staged_testimonials',
  {
    id: serial('id').primaryKey(),
    submission: integer('submission_id')
      .notNull()
      .references(() => community_submissions.id, {
        onDelete: 'set null',
      }),
    contextKind: enum_staged_testimonials_context_kind('context_kind'),
    contextDate: timestamp('context_date', { mode: 'string', withTimezone: true, precision: 3 }),
    quote: varchar('quote').notNull(),
    rating: numeric('rating', { mode: 'number' }),
    consentToPublish: boolean('consent_to_publish').default(false),
    reviewStatus: enum_staged_testimonials_review_status('review_status')
      .notNull()
      .default('pending'),
    reviewNotes: varchar('review_notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('staged_testimonials_submission_idx').on(columns.submission),
    index('staged_testimonials_context_kind_idx').on(columns.contextKind),
    index('staged_testimonials_context_date_idx').on(columns.contextDate),
    index('staged_testimonials_review_status_idx').on(columns.reviewStatus),
    index('staged_testimonials_updated_at_idx').on(columns.updatedAt),
    index('staged_testimonials_created_at_idx').on(columns.createdAt),
  ],
)

export const staged_testimonials_rels = pgTable(
  'staged_testimonials_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    eventsID: integer('events_id'),
    programsID: integer('programs_id'),
  },
  (columns) => [
    index('staged_testimonials_rels_order_idx').on(columns.order),
    index('staged_testimonials_rels_parent_idx').on(columns.parent),
    index('staged_testimonials_rels_path_idx').on(columns.path),
    index('staged_testimonials_rels_events_id_idx').on(columns.eventsID),
    index('staged_testimonials_rels_programs_id_idx').on(columns.programsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [staged_testimonials.id],
      name: 'staged_testimonials_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'staged_testimonials_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'staged_testimonials_rels_programs_fk',
    }).onDelete('cascade'),
  ],
)

export const staged_engagement_impacts = pgTable(
  'staged_engagement_impacts',
  {
    id: serial('id').primaryKey(),
    submission: integer('submission_id')
      .notNull()
      .references(() => community_submissions.id, {
        onDelete: 'set null',
      }),
    contextKind: enum_staged_engagement_impacts_context_kind('context_kind').notNull(),
    type: enum_staged_engagement_impacts_type('type').notNull(),
    typeOther: varchar('type_other'),
    summary: varchar('summary').notNull(),
    evidenceUrl: varchar('evidence_url'),
    aissaInfluenceScore: numeric('aissa_influence_score', { mode: 'number' }),
    actionCategory: enum_staged_engagement_impacts_action_category('action_category'),
    reviewStatus: enum_staged_engagement_impacts_review_status('review_status')
      .notNull()
      .default('pending'),
    reviewNotes: varchar('review_notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('staged_engagement_impacts_submission_idx').on(columns.submission),
    index('staged_engagement_impacts_context_kind_idx').on(columns.contextKind),
    index('staged_engagement_impacts_review_status_idx').on(columns.reviewStatus),
    index('staged_engagement_impacts_updated_at_idx').on(columns.updatedAt),
    index('staged_engagement_impacts_created_at_idx').on(columns.createdAt),
  ],
)

export const staged_engagement_impacts_rels = pgTable(
  'staged_engagement_impacts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    eventsID: integer('events_id'),
    programsID: integer('programs_id'),
  },
  (columns) => [
    index('staged_engagement_impacts_rels_order_idx').on(columns.order),
    index('staged_engagement_impacts_rels_parent_idx').on(columns.parent),
    index('staged_engagement_impacts_rels_path_idx').on(columns.path),
    index('staged_engagement_impacts_rels_events_id_idx').on(columns.eventsID),
    index('staged_engagement_impacts_rels_programs_id_idx').on(columns.programsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [staged_engagement_impacts.id],
      name: 'staged_engagement_impacts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'staged_engagement_impacts_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'staged_engagement_impacts_rels_programs_fk',
    }).onDelete('cascade'),
  ],
)

export const engagements = pgTable(
  'engagements',
  {
    id: serial('id').primaryKey(),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    type: enum_engagements_type('type').notNull(),
    typeOther: varchar('type_other'),
    contextKind: enum_engagements_context_kind('context_kind').notNull(),
    contextDate: timestamp('context_date', { mode: 'string', withTimezone: true, precision: 3 }),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    rating: numeric('rating', { mode: 'number' }),
    wouldRecommend: numeric('would_recommend', { mode: 'number' }),
    engagement_status: enum_engagements_engagement_status('engagement_status'),
    metadata: jsonb('metadata'),
    delta_capability: numeric('delta_capability', { mode: 'number' }),
    delta_network_size: numeric('delta_network_size', { mode: 'number' }),
    outcome_career_intent: enum_engagements_outcome_career_intent('outcome_career_intent'),
    outcome_project_status: enum_engagements_outcome_project_status('outcome_project_status'),
    careerImpact: enum_engagements_career_impact('career_impact'),
    pre_survey_submission: integer('pre_survey_submission_id').references(
      () => feedback_submissions.id,
      {
        onDelete: 'set null',
      },
    ),
    post_survey_submission: integer('post_survey_submission_id').references(
      () => feedback_submissions.id,
      {
        onDelete: 'set null',
      },
    ),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('engagements_person_idx').on(columns.person),
    index('engagements_context_kind_idx').on(columns.contextKind),
    index('engagements_context_date_idx').on(columns.contextDate),
    index('engagements_pre_survey_submission_idx').on(columns.pre_survey_submission),
    index('engagements_post_survey_submission_idx').on(columns.post_survey_submission),
    index('engagements_updated_at_idx').on(columns.updatedAt),
    index('engagements_created_at_idx').on(columns.createdAt),
  ],
)

export const engagements_rels = pgTable(
  'engagements_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    eventsID: integer('events_id'),
    programsID: integer('programs_id'),
    cohortsID: integer('cohorts_id'),
  },
  (columns) => [
    index('engagements_rels_order_idx').on(columns.order),
    index('engagements_rels_parent_idx').on(columns.parent),
    index('engagements_rels_path_idx').on(columns.path),
    index('engagements_rels_events_id_idx').on(columns.eventsID),
    index('engagements_rels_programs_id_idx').on(columns.programsID),
    index('engagements_rels_cohorts_id_idx').on(columns.cohortsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [engagements.id],
      name: 'engagements_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'engagements_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'engagements_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cohortsID']],
      foreignColumns: [cohorts.id],
      name: 'engagements_rels_cohorts_fk',
    }).onDelete('cascade'),
  ],
)

export const engagement_impacts = pgTable(
  'engagement_impacts',
  {
    id: serial('id').primaryKey(),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    engagement: integer('engagement_id').references(() => engagements.id, {
      onDelete: 'set null',
    }),
    affiliatedOrganisation: integer('affiliated_organisation_id').references(
      () => organisations.id,
      {
        onDelete: 'set null',
      },
    ),
    type: enum_engagement_impacts_type('type').notNull(),
    typeOther: varchar('type_other'),
    summary: varchar('summary').notNull(),
    evidenceUrl: varchar('evidence_url'),
    isVerified: boolean('is_verified').default(false),
    aissa_influence_score: numeric('aissa_influence_score', { mode: 'number' }),
    source_submission: integer('source_submission_id').references(() => feedback_submissions.id, {
      onDelete: 'set null',
    }),
    action_category: enum_engagement_impacts_action_category('action_category'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('engagement_impacts_person_idx').on(columns.person),
    index('engagement_impacts_engagement_idx').on(columns.engagement),
    index('engagement_impacts_affiliated_organisation_idx').on(columns.affiliatedOrganisation),
    index('engagement_impacts_source_submission_idx').on(columns.source_submission),
    index('engagement_impacts_updated_at_idx').on(columns.updatedAt),
    index('engagement_impacts_created_at_idx').on(columns.createdAt),
  ],
)

export const testimonials = pgTable(
  'testimonials',
  {
    id: serial('id').primaryKey(),
    person: integer('person_id').references(() => persons.id, {
      onDelete: 'set null',
    }),
    contextKind: enum_testimonials_context_kind('context_kind'),
    contextDate: timestamp('context_date', { mode: 'string', withTimezone: true, precision: 3 }),
    quote: varchar('quote').notNull(),
    attributionName: varchar('attribution_name'),
    attributionTitle: varchar('attribution_title'),
    rating: numeric('rating', { mode: 'number' }),
    priorityScore: numeric('priority_score', { mode: 'number' }).default(50),
    isPublished: boolean('is_published').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('testimonials_person_idx').on(columns.person),
    index('testimonials_context_kind_idx').on(columns.contextKind),
    index('testimonials_context_date_idx').on(columns.contextDate),
    index('testimonials_updated_at_idx').on(columns.updatedAt),
    index('testimonials_created_at_idx').on(columns.createdAt),
  ],
)

export const testimonials_rels = pgTable(
  'testimonials_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    eventsID: integer('events_id'),
    programsID: integer('programs_id'),
    cohortsID: integer('cohorts_id'),
  },
  (columns) => [
    index('testimonials_rels_order_idx').on(columns.order),
    index('testimonials_rels_parent_idx').on(columns.parent),
    index('testimonials_rels_path_idx').on(columns.path),
    index('testimonials_rels_events_id_idx').on(columns.eventsID),
    index('testimonials_rels_programs_id_idx').on(columns.programsID),
    index('testimonials_rels_cohorts_id_idx').on(columns.cohortsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [testimonials.id],
      name: 'testimonials_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'testimonials_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'testimonials_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cohortsID']],
      foreignColumns: [cohorts.id],
      name: 'testimonials_rels_cohorts_fk',
    }).onDelete('cascade'),
  ],
)

export const feedback_submissions = pgTable(
  'feedback_submissions',
  {
    id: serial('id').primaryKey(),
    source: enum_feedback_submissions_source('source').notNull(),
    typeOther: varchar('type_other'),
    tallyFormId: varchar('tally_form_id'),
    workflowType: enum_feedback_submissions_workflow_type('workflow_type'),
    processingStatus:
      enum_feedback_submissions_processing_status('processing_status').default('pending'),
    processingError: varchar('processing_error'),
    submittedAt: timestamp('submitted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    externalSubmissionId: varchar('external_submission_id'),
    externalRespondentId: varchar('external_respondent_id'),
    person: integer('person_id').references(() => persons.id, {
      onDelete: 'set null',
    }),
    externalIdentity: integer('external_identity_id').references(() => external_identities.id, {
      onDelete: 'set null',
    }),
    contextKind: enum_feedback_submissions_context_kind('context_kind'),
    contextDate: timestamp('context_date', { mode: 'string', withTimezone: true, precision: 3 }),
    rating: numeric('rating', { mode: 'number' }),
    wouldRecommend: numeric('would_recommend', { mode: 'number' }),
    beneficialAspects: varchar('beneficial_aspects'),
    improvements: varchar('improvements'),
    futureEvents: varchar('future_events'),
    consentToPublishQuote: boolean('consent_to_publish_quote').default(false),
    answers: jsonb('answers'),
    metadata: jsonb('metadata'),
    formType: enum_feedback_submissions_form_type('form_type'),
    isFirstTimeAttendee: boolean('is_first_time_attendee').default(false),
    marketingSource: enum_feedback_submissions_marketing_source('marketing_source'),
    selfReportedCapability: numeric('self_reported_capability', { mode: 'number' }),
    networkSize: numeric('network_size', { mode: 'number' }),
    understandingOfRisks: numeric('understanding_of_risks', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('feedback_submissions_source_idx').on(columns.source),
    index('feedback_submissions_tally_form_id_idx').on(columns.tallyFormId),
    index('feedback_submissions_workflow_type_idx').on(columns.workflowType),
    index('feedback_submissions_processing_status_idx').on(columns.processingStatus),
    index('feedback_submissions_submitted_at_idx').on(columns.submittedAt),
    index('feedback_submissions_external_submission_id_idx').on(columns.externalSubmissionId),
    index('feedback_submissions_external_respondent_id_idx').on(columns.externalRespondentId),
    index('feedback_submissions_person_idx').on(columns.person),
    index('feedback_submissions_external_identity_idx').on(columns.externalIdentity),
    index('feedback_submissions_context_kind_idx').on(columns.contextKind),
    index('feedback_submissions_context_date_idx').on(columns.contextDate),
    index('feedback_submissions_updated_at_idx').on(columns.updatedAt),
    index('feedback_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const feedback_submissions_rels = pgTable(
  'feedback_submissions_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    eventsID: integer('events_id'),
    programsID: integer('programs_id'),
    cohortsID: integer('cohorts_id'),
  },
  (columns) => [
    index('feedback_submissions_rels_order_idx').on(columns.order),
    index('feedback_submissions_rels_parent_idx').on(columns.parent),
    index('feedback_submissions_rels_path_idx').on(columns.path),
    index('feedback_submissions_rels_events_id_idx').on(columns.eventsID),
    index('feedback_submissions_rels_programs_id_idx').on(columns.programsID),
    index('feedback_submissions_rels_cohorts_id_idx').on(columns.cohortsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [feedback_submissions.id],
      name: 'feedback_submissions_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'feedback_submissions_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'feedback_submissions_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cohortsID']],
      foreignColumns: [cohorts.id],
      name: 'feedback_submissions_rels_cohorts_fk',
    }).onDelete('cascade'),
  ],
)

export const persons = pgTable(
  'persons',
  {
    id: serial('id').primaryKey(),
    email: varchar('email').notNull(),
    fullName: varchar('full_name').notNull(),
    preferredName: varchar('preferred_name'),
    personTag: varchar('person_tag').default('Community Member'),
    bio: varchar('bio'),
    websiteUrl: varchar('website_url'),
    organisation: varchar('organisation'),
    headshot: integer('headshot_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    joinedAt: timestamp('joined_at', { mode: 'string', withTimezone: true, precision: 3 }),
    isPublished: boolean('is_published').default(false),
    highlight: boolean('highlight').default(false),
    featuredStory: jsonb('featured_story'),
    metadata: jsonb('metadata'),
    totalEngagements: numeric('total_engagements', { mode: 'number' }),
    totalImpacts: numeric('total_impacts', { mode: 'number' }),
    totalContributions: numeric('total_contributions', { mode: 'number' }),
    firstEngagementDate: timestamp('first_engagement_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    lastEngagementDate: timestamp('last_engagement_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    baselineCapability: numeric('baseline_capability', { mode: 'number' }),
    baselineNetworkSize: numeric('baseline_network_size', { mode: 'number' }),
    baselineUnderstanding: numeric('baseline_understanding', { mode: 'number' }),
    current_impact_stage: enum_persons_current_impact_stage('current_impact_stage'),
    total_engagement_hours: numeric('total_engagement_hours', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('persons_email_idx').on(columns.email),
    index('persons_headshot_idx').on(columns.headshot),
    index('persons_updated_at_idx').on(columns.updatedAt),
    index('persons_created_at_idx').on(columns.createdAt),
  ],
)

export const external_identities = pgTable(
  'external_identities',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    provider: enum_external_identities_provider('provider').notNull(),
    externalId: varchar('external_id').notNull(),
    person: integer('person_id').references(() => persons.id, {
      onDelete: 'set null',
    }),
    email: varchar('email'),
    phone: varchar('phone'),
    firstSeenAt: timestamp('first_seen_at', { mode: 'string', withTimezone: true, precision: 3 }),
    lastSeenAt: timestamp('last_seen_at', { mode: 'string', withTimezone: true, precision: 3 }),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('external_identities_key_idx').on(columns.key),
    index('external_identities_provider_idx').on(columns.provider),
    index('external_identities_external_id_idx').on(columns.externalId),
    index('external_identities_person_idx').on(columns.person),
    index('external_identities_email_idx').on(columns.email),
    index('external_identities_phone_idx').on(columns.phone),
    index('external_identities_updated_at_idx').on(columns.updatedAt),
    index('external_identities_created_at_idx').on(columns.createdAt),
  ],
)

export const organisations = pgTable(
  'organisations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    type: enum_organisations_type('type'),
    website: varchar('website'),
    description: varchar('description'),
    isPartnershipActive: boolean('is_partnership_active').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('organisations_updated_at_idx').on(columns.updatedAt),
    index('organisations_created_at_idx').on(columns.createdAt),
  ],
)

export const partnerships = pgTable(
  'partnerships',
  {
    id: serial('id').primaryKey(),
    organisation: integer('organisation_id')
      .notNull()
      .references(() => organisations.id, {
        onDelete: 'set null',
      }),
    type: enum_partnerships_type('type').notNull(),
    description: varchar('description'),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('partnerships_organisation_idx').on(columns.organisation),
    index('partnerships_updated_at_idx').on(columns.updatedAt),
    index('partnerships_created_at_idx').on(columns.createdAt),
  ],
)

export const programs_images = pgTable(
  'programs_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    isHighlighted: boolean('is_highlighted').default(false),
    caption: varchar('caption'),
  },
  (columns) => [
    index('programs_images_order_idx').on(columns._order),
    index('programs_images_parent_id_idx').on(columns._parentID),
    index('programs_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [programs.id],
      name: 'programs_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const programs = pgTable(
  'programs',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    name: varchar('name').notNull(),
    type: enum_programs_type('type').notNull(),
    typeOther: varchar('type_other'),
    partnership: integer('partnership_id').references(() => partnerships.id, {
      onDelete: 'set null',
    }),
    description: jsonb('description'),
    applicationCount: numeric('application_count', { mode: 'number' }),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('programs_slug_idx').on(columns.slug),
    index('programs_partnership_idx').on(columns.partnership),
    index('programs_updated_at_idx').on(columns.updatedAt),
    index('programs_created_at_idx').on(columns.createdAt),
  ],
)

export const cohorts_images = pgTable(
  'cohorts_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    isHighlighted: boolean('is_highlighted').default(false),
    caption: varchar('caption'),
  },
  (columns) => [
    index('cohorts_images_order_idx').on(columns._order),
    index('cohorts_images_parent_id_idx').on(columns._parentID),
    index('cohorts_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cohorts.id],
      name: 'cohorts_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cohorts = pgTable(
  'cohorts',
  {
    id: serial('id').primaryKey(),
    program: integer('program_id')
      .notNull()
      .references(() => programs.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    acceptedCount: numeric('accepted_count', { mode: 'number' }),
    completionCount: numeric('completion_count', { mode: 'number' }),
    completionRate: numeric('completion_rate', { mode: 'number' }),
    averageRating: numeric('average_rating', { mode: 'number' }),
    dropoutRate: numeric('dropout_rate', { mode: 'number' }),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('cohorts_program_idx').on(columns.program),
    uniqueIndex('cohorts_slug_idx').on(columns.slug),
    index('cohorts_updated_at_idx').on(columns.updatedAt),
    index('cohorts_created_at_idx').on(columns.createdAt),
  ],
)

export const events_images = pgTable(
  'events_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    isHighlighted: boolean('is_highlighted').default(false),
    caption: varchar('caption'),
  },
  (columns) => [
    index('events_images_order_idx').on(columns._order),
    index('events_images_parent_id_idx').on(columns._parentID),
    index('events_images_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [events.id],
      name: 'events_images_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const events = pgTable(
  'events',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    name: varchar('name').notNull(),
    type: enum_events_type('type').notNull(),
    typeOther: varchar('type_other'),
    organiser: integer('organiser_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    eventDate: timestamp('event_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    attendanceCount: numeric('attendance_count', { mode: 'number' }),
    location: varchar('location'),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('events_slug_idx').on(columns.slug),
    index('events_organiser_idx').on(columns.organiser),
    index('events_updated_at_idx').on(columns.updatedAt),
    index('events_created_at_idx').on(columns.createdAt),
  ],
)

export const projects = pgTable(
  'projects',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    title: varchar('title').notNull(),
    type: enum_projects_type('type').notNull(),
    typeOther: varchar('type_other'),
    project_status: enum_projects_project_status('project_status').default('in_progress'),
    tier: enum_projects_tier('tier'),
    program: integer('program_id').references(() => programs.id, {
      onDelete: 'set null',
    }),
    linkUrl: varchar('link_url'),
    repositoryUrl: varchar('repository_url'),
    isPublished: boolean('is_published').default(false),
    metadata: jsonb('metadata'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('projects_slug_idx').on(columns.slug),
    index('projects_program_idx').on(columns.program),
    index('projects_updated_at_idx').on(columns.updatedAt),
    index('projects_created_at_idx').on(columns.createdAt),
  ],
)

export const grants = pgTable(
  'grants',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    currency: enum_grants_currency('currency').default('ZAR'),
    funder: varchar('funder'),
    organisationalProject: varchar('organisational_project'),
    dateAwarded: timestamp('date_awarded', { mode: 'string', withTimezone: true, precision: 3 }),
    description: jsonb('description'),
    status: enum_grants_status('status'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('grants_updated_at_idx').on(columns.updatedAt),
    index('grants_created_at_idx').on(columns.createdAt),
  ],
)

export const research_authors = pgTable(
  'research_authors',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    person: integer('person_id').references(() => persons.id, {
      onDelete: 'set null',
    }),
    name: varchar('name'),
  },
  (columns) => [
    index('research_authors_order_idx').on(columns._order),
    index('research_authors_parent_id_idx').on(columns._parentID),
    index('research_authors_person_idx').on(columns.person),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [research.id],
      name: 'research_authors_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const research_keywords = pgTable(
  'research_keywords',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    keyword: varchar('keyword').notNull(),
  },
  (columns) => [
    index('research_keywords_order_idx').on(columns._order),
    index('research_keywords_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [research.id],
      name: 'research_keywords_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const research = pgTable(
  'research',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    abstract: varchar('abstract'),
    arxivLink: varchar('arxiv_link'),
    acceptedVenue: varchar('accepted_venue'),
    venueType: enum_research_venue_type('venue_type'),
    publicationDate: timestamp('publication_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    doi: varchar('doi'),
    relatedProject: integer('related_project_id').references(() => projects.id, {
      onDelete: 'set null',
    }),
    status: enum_research_status('status').default('draft'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('research_related_project_idx').on(columns.relatedProject),
    index('research_updated_at_idx').on(columns.updatedAt),
    index('research_created_at_idx').on(columns.createdAt),
  ],
)

export const event_hosts = pgTable(
  'event_hosts',
  {
    id: serial('id').primaryKey(),
    event: integer('event_id')
      .notNull()
      .references(() => events.id, {
        onDelete: 'set null',
      }),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('event_hosts_event_idx').on(columns.event),
    index('event_hosts_person_idx').on(columns.person),
    index('event_hosts_updated_at_idx').on(columns.updatedAt),
    index('event_hosts_created_at_idx').on(columns.createdAt),
  ],
)

export const project_contributors = pgTable(
  'project_contributors',
  {
    id: serial('id').primaryKey(),
    project: integer('project_id')
      .notNull()
      .references(() => projects.id, {
        onDelete: 'set null',
      }),
    person: integer('person_id')
      .notNull()
      .references(() => persons.id, {
        onDelete: 'set null',
      }),
    role: enum_project_contributors_role('role').notNull(),
    roleOther: varchar('role_other'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('project_contributors_project_idx').on(columns.project),
    index('project_contributors_person_idx').on(columns.person),
    index('project_contributors_updated_at_idx').on(columns.updatedAt),
    index('project_contributors_created_at_idx').on(columns.createdAt),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    _key: varchar('_key'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_jobs_log = pgTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    executedAt: timestamp('executed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug('task_slug').notNull(),
    taskID: varchar('task_i_d').notNull(),
    input: jsonb('input'),
    output: jsonb('output'),
    state: enum_payload_jobs_log_state('state').notNull(),
    error: jsonb('error'),
  },
  (columns) => [
    index('payload_jobs_log_order_idx').on(columns._order),
    index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_jobs = pgTable(
  'payload_jobs',
  {
    id: serial('id').primaryKey(),
    input: jsonb('input'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    totalTried: numeric('total_tried', { mode: 'number' }).default(0),
    hasError: boolean('has_error').default(false),
    error: jsonb('error'),
    taskSlug: enum_payload_jobs_task_slug('task_slug'),
    queue: varchar('queue').default('default'),
    waitUntil: timestamp('wait_until', { mode: 'string', withTimezone: true, precision: 3 }),
    processing: boolean('processing').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_jobs_completed_at_idx').on(columns.completedAt),
    index('payload_jobs_total_tried_idx').on(columns.totalTried),
    index('payload_jobs_has_error_idx').on(columns.hasError),
    index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    index('payload_jobs_queue_idx').on(columns.queue),
    index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    index('payload_jobs_processing_idx').on(columns.processing),
    index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    index('payload_jobs_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'community-submissionsID': integer('community_submissions_id'),
    'staged-person-updatesID': integer('staged_person_updates_id'),
    'staged-engagementsID': integer('staged_engagements_id'),
    'staged-engagement-removalsID': integer('staged_engagement_removals_id'),
    'staged-testimonialsID': integer('staged_testimonials_id'),
    'staged-engagement-impactsID': integer('staged_engagement_impacts_id'),
    engagementsID: integer('engagements_id'),
    'engagement-impactsID': integer('engagement_impacts_id'),
    testimonialsID: integer('testimonials_id'),
    'feedback-submissionsID': integer('feedback_submissions_id'),
    personsID: integer('persons_id'),
    'external-identitiesID': integer('external_identities_id'),
    organisationsID: integer('organisations_id'),
    partnershipsID: integer('partnerships_id'),
    programsID: integer('programs_id'),
    cohortsID: integer('cohorts_id'),
    eventsID: integer('events_id'),
    projectsID: integer('projects_id'),
    grantsID: integer('grants_id'),
    researchID: integer('research_id'),
    'event-hostsID': integer('event_hosts_id'),
    'project-contributorsID': integer('project_contributors_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_community_submissions_id_idx').on(
      columns['community-submissionsID'],
    ),
    index('payload_locked_documents_rels_staged_person_updates_id_idx').on(
      columns['staged-person-updatesID'],
    ),
    index('payload_locked_documents_rels_staged_engagements_id_idx').on(
      columns['staged-engagementsID'],
    ),
    index('payload_locked_documents_rels_staged_engagement_removals_idx').on(
      columns['staged-engagement-removalsID'],
    ),
    index('payload_locked_documents_rels_staged_testimonials_id_idx').on(
      columns['staged-testimonialsID'],
    ),
    index('payload_locked_documents_rels_staged_engagement_impacts__idx').on(
      columns['staged-engagement-impactsID'],
    ),
    index('payload_locked_documents_rels_engagements_id_idx').on(columns.engagementsID),
    index('payload_locked_documents_rels_engagement_impacts_id_idx').on(
      columns['engagement-impactsID'],
    ),
    index('payload_locked_documents_rels_testimonials_id_idx').on(columns.testimonialsID),
    index('payload_locked_documents_rels_feedback_submissions_id_idx').on(
      columns['feedback-submissionsID'],
    ),
    index('payload_locked_documents_rels_persons_id_idx').on(columns.personsID),
    index('payload_locked_documents_rels_external_identities_id_idx').on(
      columns['external-identitiesID'],
    ),
    index('payload_locked_documents_rels_organisations_id_idx').on(columns.organisationsID),
    index('payload_locked_documents_rels_partnerships_id_idx').on(columns.partnershipsID),
    index('payload_locked_documents_rels_programs_id_idx').on(columns.programsID),
    index('payload_locked_documents_rels_cohorts_id_idx').on(columns.cohortsID),
    index('payload_locked_documents_rels_events_id_idx').on(columns.eventsID),
    index('payload_locked_documents_rels_projects_id_idx').on(columns.projectsID),
    index('payload_locked_documents_rels_grants_id_idx').on(columns.grantsID),
    index('payload_locked_documents_rels_research_id_idx').on(columns.researchID),
    index('payload_locked_documents_rels_event_hosts_id_idx').on(columns['event-hostsID']),
    index('payload_locked_documents_rels_project_contributors_id_idx').on(
      columns['project-contributorsID'],
    ),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['community-submissionsID']],
      foreignColumns: [community_submissions.id],
      name: 'payload_locked_documents_rels_community_submissions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['staged-person-updatesID']],
      foreignColumns: [staged_person_updates.id],
      name: 'payload_locked_documents_rels_staged_person_updates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['staged-engagementsID']],
      foreignColumns: [staged_engagements.id],
      name: 'payload_locked_documents_rels_staged_engagements_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['staged-engagement-removalsID']],
      foreignColumns: [staged_engagement_removals.id],
      name: 'payload_locked_documents_rels_staged_engagement_removals_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['staged-testimonialsID']],
      foreignColumns: [staged_testimonials.id],
      name: 'payload_locked_documents_rels_staged_testimonials_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['staged-engagement-impactsID']],
      foreignColumns: [staged_engagement_impacts.id],
      name: 'payload_locked_documents_rels_staged_engagement_impacts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['engagementsID']],
      foreignColumns: [engagements.id],
      name: 'payload_locked_documents_rels_engagements_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['engagement-impactsID']],
      foreignColumns: [engagement_impacts.id],
      name: 'payload_locked_documents_rels_engagement_impacts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['testimonialsID']],
      foreignColumns: [testimonials.id],
      name: 'payload_locked_documents_rels_testimonials_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['feedback-submissionsID']],
      foreignColumns: [feedback_submissions.id],
      name: 'payload_locked_documents_rels_feedback_submissions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['personsID']],
      foreignColumns: [persons.id],
      name: 'payload_locked_documents_rels_persons_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['external-identitiesID']],
      foreignColumns: [external_identities.id],
      name: 'payload_locked_documents_rels_external_identities_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['organisationsID']],
      foreignColumns: [organisations.id],
      name: 'payload_locked_documents_rels_organisations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['partnershipsID']],
      foreignColumns: [partnerships.id],
      name: 'payload_locked_documents_rels_partnerships_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'payload_locked_documents_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cohortsID']],
      foreignColumns: [cohorts.id],
      name: 'payload_locked_documents_rels_cohorts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['eventsID']],
      foreignColumns: [events.id],
      name: 'payload_locked_documents_rels_events_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'payload_locked_documents_rels_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['grantsID']],
      foreignColumns: [grants.id],
      name: 'payload_locked_documents_rels_grants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['researchID']],
      foreignColumns: [research.id],
      name: 'payload_locked_documents_rels_research_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['event-hostsID']],
      foreignColumns: [event_hosts.id],
      name: 'payload_locked_documents_rels_event_hosts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['project-contributorsID']],
      foreignColumns: [project_contributors.id],
      name: 'payload_locked_documents_rels_project_contributors_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_community_submissions = relations(community_submissions, ({ one }) => ({
  person: one(persons, {
    fields: [community_submissions.person],
    references: [persons.id],
    relationName: 'person',
  }),
  reviewedBy: one(users, {
    fields: [community_submissions.reviewedBy],
    references: [users.id],
    relationName: 'reviewedBy',
  }),
}))
export const relations_staged_person_updates = relations(staged_person_updates, ({ one }) => ({
  submission: one(community_submissions, {
    fields: [staged_person_updates.submission],
    references: [community_submissions.id],
    relationName: 'submission',
  }),
}))
export const relations_staged_engagements_rels = relations(staged_engagements_rels, ({ one }) => ({
  parent: one(staged_engagements, {
    fields: [staged_engagements_rels.parent],
    references: [staged_engagements.id],
    relationName: '_rels',
  }),
  eventsID: one(events, {
    fields: [staged_engagements_rels.eventsID],
    references: [events.id],
    relationName: 'events',
  }),
  programsID: one(programs, {
    fields: [staged_engagements_rels.programsID],
    references: [programs.id],
    relationName: 'programs',
  }),
}))
export const relations_staged_engagements = relations(staged_engagements, ({ one, many }) => ({
  submission: one(community_submissions, {
    fields: [staged_engagements.submission],
    references: [community_submissions.id],
    relationName: 'submission',
  }),
  existingEngagement: one(engagements, {
    fields: [staged_engagements.existingEngagement],
    references: [engagements.id],
    relationName: 'existingEngagement',
  }),
  _rels: many(staged_engagements_rels, {
    relationName: '_rels',
  }),
}))
export const relations_staged_engagement_removals = relations(
  staged_engagement_removals,
  ({ one }) => ({
    submission: one(community_submissions, {
      fields: [staged_engagement_removals.submission],
      references: [community_submissions.id],
      relationName: 'submission',
    }),
    engagement: one(engagements, {
      fields: [staged_engagement_removals.engagement],
      references: [engagements.id],
      relationName: 'engagement',
    }),
  }),
)
export const relations_staged_testimonials_rels = relations(
  staged_testimonials_rels,
  ({ one }) => ({
    parent: one(staged_testimonials, {
      fields: [staged_testimonials_rels.parent],
      references: [staged_testimonials.id],
      relationName: '_rels',
    }),
    eventsID: one(events, {
      fields: [staged_testimonials_rels.eventsID],
      references: [events.id],
      relationName: 'events',
    }),
    programsID: one(programs, {
      fields: [staged_testimonials_rels.programsID],
      references: [programs.id],
      relationName: 'programs',
    }),
  }),
)
export const relations_staged_testimonials = relations(staged_testimonials, ({ one, many }) => ({
  submission: one(community_submissions, {
    fields: [staged_testimonials.submission],
    references: [community_submissions.id],
    relationName: 'submission',
  }),
  _rels: many(staged_testimonials_rels, {
    relationName: '_rels',
  }),
}))
export const relations_staged_engagement_impacts_rels = relations(
  staged_engagement_impacts_rels,
  ({ one }) => ({
    parent: one(staged_engagement_impacts, {
      fields: [staged_engagement_impacts_rels.parent],
      references: [staged_engagement_impacts.id],
      relationName: '_rels',
    }),
    eventsID: one(events, {
      fields: [staged_engagement_impacts_rels.eventsID],
      references: [events.id],
      relationName: 'events',
    }),
    programsID: one(programs, {
      fields: [staged_engagement_impacts_rels.programsID],
      references: [programs.id],
      relationName: 'programs',
    }),
  }),
)
export const relations_staged_engagement_impacts = relations(
  staged_engagement_impacts,
  ({ one, many }) => ({
    submission: one(community_submissions, {
      fields: [staged_engagement_impacts.submission],
      references: [community_submissions.id],
      relationName: 'submission',
    }),
    _rels: many(staged_engagement_impacts_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_engagements_rels = relations(engagements_rels, ({ one }) => ({
  parent: one(engagements, {
    fields: [engagements_rels.parent],
    references: [engagements.id],
    relationName: '_rels',
  }),
  eventsID: one(events, {
    fields: [engagements_rels.eventsID],
    references: [events.id],
    relationName: 'events',
  }),
  programsID: one(programs, {
    fields: [engagements_rels.programsID],
    references: [programs.id],
    relationName: 'programs',
  }),
  cohortsID: one(cohorts, {
    fields: [engagements_rels.cohortsID],
    references: [cohorts.id],
    relationName: 'cohorts',
  }),
}))
export const relations_engagements = relations(engagements, ({ one, many }) => ({
  person: one(persons, {
    fields: [engagements.person],
    references: [persons.id],
    relationName: 'person',
  }),
  pre_survey_submission: one(feedback_submissions, {
    fields: [engagements.pre_survey_submission],
    references: [feedback_submissions.id],
    relationName: 'pre_survey_submission',
  }),
  post_survey_submission: one(feedback_submissions, {
    fields: [engagements.post_survey_submission],
    references: [feedback_submissions.id],
    relationName: 'post_survey_submission',
  }),
  _rels: many(engagements_rels, {
    relationName: '_rels',
  }),
}))
export const relations_engagement_impacts = relations(engagement_impacts, ({ one }) => ({
  person: one(persons, {
    fields: [engagement_impacts.person],
    references: [persons.id],
    relationName: 'person',
  }),
  engagement: one(engagements, {
    fields: [engagement_impacts.engagement],
    references: [engagements.id],
    relationName: 'engagement',
  }),
  affiliatedOrganisation: one(organisations, {
    fields: [engagement_impacts.affiliatedOrganisation],
    references: [organisations.id],
    relationName: 'affiliatedOrganisation',
  }),
  source_submission: one(feedback_submissions, {
    fields: [engagement_impacts.source_submission],
    references: [feedback_submissions.id],
    relationName: 'source_submission',
  }),
}))
export const relations_testimonials_rels = relations(testimonials_rels, ({ one }) => ({
  parent: one(testimonials, {
    fields: [testimonials_rels.parent],
    references: [testimonials.id],
    relationName: '_rels',
  }),
  eventsID: one(events, {
    fields: [testimonials_rels.eventsID],
    references: [events.id],
    relationName: 'events',
  }),
  programsID: one(programs, {
    fields: [testimonials_rels.programsID],
    references: [programs.id],
    relationName: 'programs',
  }),
  cohortsID: one(cohorts, {
    fields: [testimonials_rels.cohortsID],
    references: [cohorts.id],
    relationName: 'cohorts',
  }),
}))
export const relations_testimonials = relations(testimonials, ({ one, many }) => ({
  person: one(persons, {
    fields: [testimonials.person],
    references: [persons.id],
    relationName: 'person',
  }),
  _rels: many(testimonials_rels, {
    relationName: '_rels',
  }),
}))
export const relations_feedback_submissions_rels = relations(
  feedback_submissions_rels,
  ({ one }) => ({
    parent: one(feedback_submissions, {
      fields: [feedback_submissions_rels.parent],
      references: [feedback_submissions.id],
      relationName: '_rels',
    }),
    eventsID: one(events, {
      fields: [feedback_submissions_rels.eventsID],
      references: [events.id],
      relationName: 'events',
    }),
    programsID: one(programs, {
      fields: [feedback_submissions_rels.programsID],
      references: [programs.id],
      relationName: 'programs',
    }),
    cohortsID: one(cohorts, {
      fields: [feedback_submissions_rels.cohortsID],
      references: [cohorts.id],
      relationName: 'cohorts',
    }),
  }),
)
export const relations_feedback_submissions = relations(feedback_submissions, ({ one, many }) => ({
  person: one(persons, {
    fields: [feedback_submissions.person],
    references: [persons.id],
    relationName: 'person',
  }),
  externalIdentity: one(external_identities, {
    fields: [feedback_submissions.externalIdentity],
    references: [external_identities.id],
    relationName: 'externalIdentity',
  }),
  _rels: many(feedback_submissions_rels, {
    relationName: '_rels',
  }),
}))
export const relations_persons = relations(persons, ({ one }) => ({
  headshot: one(media, {
    fields: [persons.headshot],
    references: [media.id],
    relationName: 'headshot',
  }),
}))
export const relations_external_identities = relations(external_identities, ({ one }) => ({
  person: one(persons, {
    fields: [external_identities.person],
    references: [persons.id],
    relationName: 'person',
  }),
}))
export const relations_organisations = relations(organisations, () => ({}))
export const relations_partnerships = relations(partnerships, ({ one }) => ({
  organisation: one(organisations, {
    fields: [partnerships.organisation],
    references: [organisations.id],
    relationName: 'organisation',
  }),
}))
export const relations_programs_images = relations(programs_images, ({ one }) => ({
  _parentID: one(programs, {
    fields: [programs_images._parentID],
    references: [programs.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [programs_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_programs = relations(programs, ({ one, many }) => ({
  partnership: one(partnerships, {
    fields: [programs.partnership],
    references: [partnerships.id],
    relationName: 'partnership',
  }),
  images: many(programs_images, {
    relationName: 'images',
  }),
}))
export const relations_cohorts_images = relations(cohorts_images, ({ one }) => ({
  _parentID: one(cohorts, {
    fields: [cohorts_images._parentID],
    references: [cohorts.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [cohorts_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_cohorts = relations(cohorts, ({ one, many }) => ({
  program: one(programs, {
    fields: [cohorts.program],
    references: [programs.id],
    relationName: 'program',
  }),
  images: many(cohorts_images, {
    relationName: 'images',
  }),
}))
export const relations_events_images = relations(events_images, ({ one }) => ({
  _parentID: one(events, {
    fields: [events_images._parentID],
    references: [events.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [events_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_events = relations(events, ({ one, many }) => ({
  organiser: one(persons, {
    fields: [events.organiser],
    references: [persons.id],
    relationName: 'organiser',
  }),
  images: many(events_images, {
    relationName: 'images',
  }),
}))
export const relations_projects = relations(projects, ({ one }) => ({
  program: one(programs, {
    fields: [projects.program],
    references: [programs.id],
    relationName: 'program',
  }),
}))
export const relations_grants = relations(grants, () => ({}))
export const relations_research_authors = relations(research_authors, ({ one }) => ({
  _parentID: one(research, {
    fields: [research_authors._parentID],
    references: [research.id],
    relationName: 'authors',
  }),
  person: one(persons, {
    fields: [research_authors.person],
    references: [persons.id],
    relationName: 'person',
  }),
}))
export const relations_research_keywords = relations(research_keywords, ({ one }) => ({
  _parentID: one(research, {
    fields: [research_keywords._parentID],
    references: [research.id],
    relationName: 'keywords',
  }),
}))
export const relations_research = relations(research, ({ one, many }) => ({
  authors: many(research_authors, {
    relationName: 'authors',
  }),
  keywords: many(research_keywords, {
    relationName: 'keywords',
  }),
  relatedProject: one(projects, {
    fields: [research.relatedProject],
    references: [projects.id],
    relationName: 'relatedProject',
  }),
}))
export const relations_event_hosts = relations(event_hosts, ({ one }) => ({
  event: one(events, {
    fields: [event_hosts.event],
    references: [events.id],
    relationName: 'event',
  }),
  person: one(persons, {
    fields: [event_hosts.person],
    references: [persons.id],
    relationName: 'person',
  }),
}))
export const relations_project_contributors = relations(project_contributors, ({ one }) => ({
  project: one(projects, {
    fields: [project_contributors.project],
    references: [projects.id],
    relationName: 'project',
  }),
  person: one(persons, {
    fields: [project_contributors.person],
    references: [persons.id],
    relationName: 'person',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    'community-submissionsID': one(community_submissions, {
      fields: [payload_locked_documents_rels['community-submissionsID']],
      references: [community_submissions.id],
      relationName: 'community-submissions',
    }),
    'staged-person-updatesID': one(staged_person_updates, {
      fields: [payload_locked_documents_rels['staged-person-updatesID']],
      references: [staged_person_updates.id],
      relationName: 'staged-person-updates',
    }),
    'staged-engagementsID': one(staged_engagements, {
      fields: [payload_locked_documents_rels['staged-engagementsID']],
      references: [staged_engagements.id],
      relationName: 'staged-engagements',
    }),
    'staged-engagement-removalsID': one(staged_engagement_removals, {
      fields: [payload_locked_documents_rels['staged-engagement-removalsID']],
      references: [staged_engagement_removals.id],
      relationName: 'staged-engagement-removals',
    }),
    'staged-testimonialsID': one(staged_testimonials, {
      fields: [payload_locked_documents_rels['staged-testimonialsID']],
      references: [staged_testimonials.id],
      relationName: 'staged-testimonials',
    }),
    'staged-engagement-impactsID': one(staged_engagement_impacts, {
      fields: [payload_locked_documents_rels['staged-engagement-impactsID']],
      references: [staged_engagement_impacts.id],
      relationName: 'staged-engagement-impacts',
    }),
    engagementsID: one(engagements, {
      fields: [payload_locked_documents_rels.engagementsID],
      references: [engagements.id],
      relationName: 'engagements',
    }),
    'engagement-impactsID': one(engagement_impacts, {
      fields: [payload_locked_documents_rels['engagement-impactsID']],
      references: [engagement_impacts.id],
      relationName: 'engagement-impacts',
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: 'testimonials',
    }),
    'feedback-submissionsID': one(feedback_submissions, {
      fields: [payload_locked_documents_rels['feedback-submissionsID']],
      references: [feedback_submissions.id],
      relationName: 'feedback-submissions',
    }),
    personsID: one(persons, {
      fields: [payload_locked_documents_rels.personsID],
      references: [persons.id],
      relationName: 'persons',
    }),
    'external-identitiesID': one(external_identities, {
      fields: [payload_locked_documents_rels['external-identitiesID']],
      references: [external_identities.id],
      relationName: 'external-identities',
    }),
    organisationsID: one(organisations, {
      fields: [payload_locked_documents_rels.organisationsID],
      references: [organisations.id],
      relationName: 'organisations',
    }),
    partnershipsID: one(partnerships, {
      fields: [payload_locked_documents_rels.partnershipsID],
      references: [partnerships.id],
      relationName: 'partnerships',
    }),
    programsID: one(programs, {
      fields: [payload_locked_documents_rels.programsID],
      references: [programs.id],
      relationName: 'programs',
    }),
    cohortsID: one(cohorts, {
      fields: [payload_locked_documents_rels.cohortsID],
      references: [cohorts.id],
      relationName: 'cohorts',
    }),
    eventsID: one(events, {
      fields: [payload_locked_documents_rels.eventsID],
      references: [events.id],
      relationName: 'events',
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: 'projects',
    }),
    grantsID: one(grants, {
      fields: [payload_locked_documents_rels.grantsID],
      references: [grants.id],
      relationName: 'grants',
    }),
    researchID: one(research, {
      fields: [payload_locked_documents_rels.researchID],
      references: [research.id],
      relationName: 'research',
    }),
    'event-hostsID': one(event_hosts, {
      fields: [payload_locked_documents_rels['event-hostsID']],
      references: [event_hosts.id],
      relationName: 'event-hosts',
    }),
    'project-contributorsID': one(project_contributors, {
      fields: [payload_locked_documents_rels['project-contributorsID']],
      references: [project_contributors.id],
      relationName: 'project-contributors',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_community_submissions_status: typeof enum_community_submissions_status
  enum_staged_person_updates_field: typeof enum_staged_person_updates_field
  enum_staged_person_updates_review_status: typeof enum_staged_person_updates_review_status
  enum_staged_engagements_context_kind: typeof enum_staged_engagements_context_kind
  enum_staged_engagements_type: typeof enum_staged_engagements_type
  enum_staged_engagements_engagement_status: typeof enum_staged_engagements_engagement_status
  enum_staged_engagements_operation: typeof enum_staged_engagements_operation
  enum_staged_engagements_review_status: typeof enum_staged_engagements_review_status
  enum_staged_engagement_removals_review_status: typeof enum_staged_engagement_removals_review_status
  enum_staged_testimonials_context_kind: typeof enum_staged_testimonials_context_kind
  enum_staged_testimonials_review_status: typeof enum_staged_testimonials_review_status
  enum_staged_engagement_impacts_context_kind: typeof enum_staged_engagement_impacts_context_kind
  enum_staged_engagement_impacts_type: typeof enum_staged_engagement_impacts_type
  enum_staged_engagement_impacts_action_category: typeof enum_staged_engagement_impacts_action_category
  enum_staged_engagement_impacts_review_status: typeof enum_staged_engagement_impacts_review_status
  enum_engagements_type: typeof enum_engagements_type
  enum_engagements_context_kind: typeof enum_engagements_context_kind
  enum_engagements_engagement_status: typeof enum_engagements_engagement_status
  enum_engagements_outcome_career_intent: typeof enum_engagements_outcome_career_intent
  enum_engagements_outcome_project_status: typeof enum_engagements_outcome_project_status
  enum_engagements_career_impact: typeof enum_engagements_career_impact
  enum_engagement_impacts_type: typeof enum_engagement_impacts_type
  enum_engagement_impacts_action_category: typeof enum_engagement_impacts_action_category
  enum_testimonials_context_kind: typeof enum_testimonials_context_kind
  enum_feedback_submissions_source: typeof enum_feedback_submissions_source
  enum_feedback_submissions_workflow_type: typeof enum_feedback_submissions_workflow_type
  enum_feedback_submissions_processing_status: typeof enum_feedback_submissions_processing_status
  enum_feedback_submissions_context_kind: typeof enum_feedback_submissions_context_kind
  enum_feedback_submissions_form_type: typeof enum_feedback_submissions_form_type
  enum_feedback_submissions_marketing_source: typeof enum_feedback_submissions_marketing_source
  enum_persons_current_impact_stage: typeof enum_persons_current_impact_stage
  enum_external_identities_provider: typeof enum_external_identities_provider
  enum_organisations_type: typeof enum_organisations_type
  enum_partnerships_type: typeof enum_partnerships_type
  enum_programs_type: typeof enum_programs_type
  enum_events_type: typeof enum_events_type
  enum_projects_type: typeof enum_projects_type
  enum_projects_project_status: typeof enum_projects_project_status
  enum_projects_tier: typeof enum_projects_tier
  enum_grants_currency: typeof enum_grants_currency
  enum_grants_status: typeof enum_grants_status
  enum_research_venue_type: typeof enum_research_venue_type
  enum_research_status: typeof enum_research_status
  enum_project_contributors_role: typeof enum_project_contributors_role
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug
  community_submissions: typeof community_submissions
  staged_person_updates: typeof staged_person_updates
  staged_engagements: typeof staged_engagements
  staged_engagements_rels: typeof staged_engagements_rels
  staged_engagement_removals: typeof staged_engagement_removals
  staged_testimonials: typeof staged_testimonials
  staged_testimonials_rels: typeof staged_testimonials_rels
  staged_engagement_impacts: typeof staged_engagement_impacts
  staged_engagement_impacts_rels: typeof staged_engagement_impacts_rels
  engagements: typeof engagements
  engagements_rels: typeof engagements_rels
  engagement_impacts: typeof engagement_impacts
  testimonials: typeof testimonials
  testimonials_rels: typeof testimonials_rels
  feedback_submissions: typeof feedback_submissions
  feedback_submissions_rels: typeof feedback_submissions_rels
  persons: typeof persons
  external_identities: typeof external_identities
  organisations: typeof organisations
  partnerships: typeof partnerships
  programs_images: typeof programs_images
  programs: typeof programs
  cohorts_images: typeof cohorts_images
  cohorts: typeof cohorts
  events_images: typeof events_images
  events: typeof events
  projects: typeof projects
  grants: typeof grants
  research_authors: typeof research_authors
  research_keywords: typeof research_keywords
  research: typeof research
  event_hosts: typeof event_hosts
  project_contributors: typeof project_contributors
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  payload_kv: typeof payload_kv
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_community_submissions: typeof relations_community_submissions
  relations_staged_person_updates: typeof relations_staged_person_updates
  relations_staged_engagements_rels: typeof relations_staged_engagements_rels
  relations_staged_engagements: typeof relations_staged_engagements
  relations_staged_engagement_removals: typeof relations_staged_engagement_removals
  relations_staged_testimonials_rels: typeof relations_staged_testimonials_rels
  relations_staged_testimonials: typeof relations_staged_testimonials
  relations_staged_engagement_impacts_rels: typeof relations_staged_engagement_impacts_rels
  relations_staged_engagement_impacts: typeof relations_staged_engagement_impacts
  relations_engagements_rels: typeof relations_engagements_rels
  relations_engagements: typeof relations_engagements
  relations_engagement_impacts: typeof relations_engagement_impacts
  relations_testimonials_rels: typeof relations_testimonials_rels
  relations_testimonials: typeof relations_testimonials
  relations_feedback_submissions_rels: typeof relations_feedback_submissions_rels
  relations_feedback_submissions: typeof relations_feedback_submissions
  relations_persons: typeof relations_persons
  relations_external_identities: typeof relations_external_identities
  relations_organisations: typeof relations_organisations
  relations_partnerships: typeof relations_partnerships
  relations_programs_images: typeof relations_programs_images
  relations_programs: typeof relations_programs
  relations_cohorts_images: typeof relations_cohorts_images
  relations_cohorts: typeof relations_cohorts
  relations_events_images: typeof relations_events_images
  relations_events: typeof relations_events
  relations_projects: typeof relations_projects
  relations_grants: typeof relations_grants
  relations_research_authors: typeof relations_research_authors
  relations_research_keywords: typeof relations_research_keywords
  relations_research: typeof relations_research
  relations_event_hosts: typeof relations_event_hosts
  relations_project_contributors: typeof relations_project_contributors
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
